spacetelescope/crds

- crds/naming.py
- crds/svn_version.py
More changes to support replacing N/A in imaps with actual rmap names automatically.
> Modified naming.py to support N/A filenames

- crds/jwst/locate.py
This overlaps with cmdline-submission branch but is semi-critical and unrelated.
> Added .lower() fix to instrument subdirectory name.

- crds/jwst/specs/nirspec_ifufore.rmap
- crds/jwst/specs/nirspec_ifupost.rmap
- crds/jwst/specs/nirspec_ifuslicer.rmap
> Initial commit of new rmaps for NIRSPEC IFU wcs transformation

- crds/git_version.py
Changes to HST ACS BIASFILE APERTURE values and substitutions for Jira-35 and CRDS #414.
> Opus 2016.1 server release

- crds/log.py
- crds/monitor.py
- crds/submit.py
- crds/web.py
Changed the default output mode for the log.divider() utility function to info()
> Log divider info

- crds/list.py
- crds/tests/profile_bestrefs.py
- crds/tests/profile_pickling.py
- crds/tests/test_config.py
Added shared profiling scripts for bestrefs and pickling used with incremental-load and pickling branches.
Changed output sort order for env vars in crds.list --config.
> Shared bestrefs and pickling profile and checkout code.

- docs/crds_users_guide/source/web_services.rst
group where it became apparent that IDs should be simplified.  The existing
code supports the simplified description already.
> Updated web services documentation based on meeting/discussion with AUI

- TESTING
- crds/rmap.py
- crds/tests/test_rmap.py
- runtests
Important fix to pickling making it effective as a file system optimization.
Renamed test cache to match GitHub repo crds-cache-test on spacetelescope.
> Pickling fix

- crds/rmap.py
Removes path-only differences from cache-to-cache comparisons.
> Rmap cache to cache diff simplification

- crds/tests/test_uses.py
- crds/uses.py
removing the obsolete "datasets using references" feature.
> Made further corrections to crds.uses and tests related to

- crds/bestrefs.py
This switch is used to dump matching parameters only for those cases that fail vs. verbose mode which dumps tons of info all the time.
> Added --log-error-headers to crds.bestrefs

- crds/config.py
- crds/data_file.py
- crds/datalvl.py
- crds/exceptions.py
- crds/jwst/specs/system_datalvl.rmap
- crds/log.py
- crds/mapping_parser.py
- crds/selectors.py
Created new VersionAfter selector.
Created reference module crds.datalvl to either illustrate how or provide the get_data_level() function to SDP.
Added type specification for SYSTEM DATLVL
> Add system datalvl

- .travis.yml
- runtests
- setup_test_cache
based on work by AstroPy and JWST teams.
> Added support for Travis CI and Coveralls

- crds/jwst/specs/nirspec_dflat.rmap
- crds/jwst/specs/nirspec_fflat.rmap
- crds/jwst/specs/nirspec_sflat.rmap
Added 3 new rmaps for nirspec flats: dflat, fflat and sflat
> Initial commit of rmaps for new nirspec flats: dflat, fflat and sflat

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/nirspec_fflat.rmap
Corrected NIRSPEC FFLAT specification parkey by dropping DETECTOR.
> Add nirspec flats 2

- crds/custom_dict.py
- crds/hst/locate.py
Fixed bug in custom_dicts get().
Fixed bug in hst.locate.match_context_key().
> Bugfix newcontext, custom_dicts get()

- crds/jwst/specs/nirspec_badshutter.rmap
Initial commit of badshutter rmap.  Only for NIRSPEC, N/A for the other instruments.
> Badshutter

- crds/jwst/specs/miri_pathloss.rmap
- crds/jwst/specs/niriss_pathloss.rmap
- crds/jwst/specs/nirspec_pathloss.rmap
NIRSPEC and MIRI are part of build 7, NIRISS is for build 7.1.  N/A for NIRCAM.
> Initial commit of PATHLOSS rmaps

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/niriss_specwcs.rmap
- crds/jwst/specs/nirspec_msaoper.rmap
Capitalized text descriptions and regenerated combined specs.
> Add niriss specwcs

- crds/data_file.py
Resolves scrambled multi-line order.
> Modified handling of data model history

- crds/jwst/pipeline.py
Refactored towards a YAML reference file that could be used to control pipeline .cfg selection
and applicable reference types for reprocessing determinations.
> Overhauled JWST pipeline awareness

- crds/bestrefs.py
- crds/data_file.py
- crds/jwst/pipeline.py
- crds/tests/test_bestrefs.py
- setup.cfg
Deferred yaml imports in jwst.pipeline
Added verbose log messages to jwst.pipeline for pipelines and reftypes
Added unit tests for header_to_reftypes().
> Updated setup.cfg to 7.0.10.

- crds/client/api.py
- crds/cmdline.py
- crds/config.py
Removes file download RPC mode and simplifies download functions.
> Simplify downloads

- crds/bestrefs.py
The default mode of the reprocessing system differences rules to determine instruments and types affected by a context change.  The types determination was overriding the types determined by EXP_TYPE and pipeline .cfg files.   Modified so that the examined types are the intersection of those affected by the rules change and those used by a particular dataset.
> Add pipeline awareness to reprocessing

- crds/rmap.py
Makes sure more/all types appear in debug output instead of vanishing.
> Added debug logging for instrument level N/A

- crds/list.py
Works with full range of context specifiers.
> Added PipelineContext version of list --required-parkeys

- crds/core/pysh.py
- scripts/crds
Adjustments to "crds" wrapper script:
1. Switched from "python" to sys.executable for subprocess.
2. Switched from os.system() to subprocess.call().
3. Simplified usage text.
> Partition core

- crds/hst/specs/combined_specs.json
- crds/hst/specs/cos_dgeofile.rmap
- crds/hst/specs/cos_xwlkfile.rmap
- crds/hst/specs/cos_ywlkfile.rmap
- crds/hst/tpns/cos_dgeo.tpn
- crds/hst/tpns/cos_dgeo_ld.tpn
- crds/hst/tpns/cos_xwalk.tpn
- crds/hst/tpns/cos_xwalk_ld.tpn
- crds/hst/tpns/cos_ywalk.tpn
- crds/hst/tpns/cos_ywalk_ld.tpn
specs and .tpns for COS DGEOFILE, XWLKFILE, YWLKFILE
> Crds jira 97, 98

- crds/client/proxy.py
- crds/tests/test_diff.py
Fix doctests broken  by changes in fitsdiff output.  Modify client proxy to avoid unwrapping error during unit tests.
> Fix fitsdiff tests

- crds/submit/submit.py
- crds/submit/web.py
Made existing lock a fatal error to avoid concurrent submissions.
> Locking improvements

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/miri_resol.rmap
> Crds jira 108

- crds/core/git_version.py
- crds/hst/tpns/acs_cte.tpn
- crds/tests/test_certify.py
Stripped down ACS CTE .tpn for conversion to WFC3-like.
> Doover 7.1.1

- crds/hst/specs/acs_pctetab.spec
- crds/hst/specs/combined_specs.json
- crds/hst/specs/wfc3_pctetab.rmap
- crds/tests/test_reftypes.py
> Removed unique_rows checks from ACS, WFC3 PCTETAB

- crds/core/selectors.py
non-tuple parameter deletions.
> Updated selectors del_match_parameter to handle singleton

- crds/bestrefs/bestrefs.py
- crds/core/heavy_client.py
- crds/tests/test_bestrefs.py
Fixed related bugs with rarely used switches/modes of bestrefs.
Modified get_pickled_mapping() to return pre-loaded mappings like asmapping().
> Added more bestrefs unit test coverage

- crds/list.py
running bestrefs and/or grepping headers one-per-line.
> Added JSON output format to crds.list --dataset-headers to support

- crds/bestrefs/bestrefs.py
- crds/core/log.py
cost of format_prefix() for multiple verbose() per-dataset log messages.
> Refactored bestrefs to add verbose_with_prefix() method to shave off

- crds/jwst/schema.py
Handles nesting "type" under "anyOf".
> Modified CRDS JWST schema loader to support revised schema

- crds/submit/submit.py
django-file-upload JSON response which changed during the recent jQuery and related package updates.
> Fixed refactoring issue with command line file submission JSONRPC interpretation

- crds/__init__.py
- crds/core/git_version.py
Updated CRDS development version to 7.1.4
> Bump version

- crds/hst/locate.py
after seeing it fail for crds sync --output=blah
> Trapped HST instrument directory symlink creation with a verbose warning

- documentation/crds_users_guide/source/index.rst
- documentation/crds_users_guide/source/installation.rst
- documentation/crds_users_guide/source/reference_conventions.rst
User's guide updates for cache locking and initial description of P_ keywords.
> Cache locking

- crds/core/config.py
- crds/core/selectors.py
- crds/jwst/gen_system_crdscfg.py
- crds/jwst/pipeline.py
Several more critical changes for the JWST pipeline module refactoring as well as some cleanup.
> Refactor pipeline

- crds/core/selectors.py
- crds/tests/test_certify.py
> Default classes

- crds/core/utils.py
Optimization for affected_datasets and bestrefs regressions,  saves 10-15% for COS,  others should  be similar.
> Added caching to utils.get_object()

- crds/certify/generic_tpn.py
- crds/certify/validators.py
- crds/io/abstract.py
- crds/io/factory.py
- crds/io/geis.py
- crds/tests/test_bestrefs.py
- crds/tests/test_certify.py
Bugfix crds.io.factory, geis:  missing __future__ absolute_import
Tweak  crds.io.abstract: bad value enumeration regex wartning vs. error
Unit test performance:  crds.bestrefs --affected-datasets smoke test
Doctest tweaks:  use of -ignore- in test_certify,  Python-2 vs. 3, excessive detail text
> Unit tests, misc

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/nircam_wavelengthrange.rmap
- crds/jwst/specs/niriss_wavelengthrange.rmap
- crds/tests/test_reftypes.py
> More wavelengthrange

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/nirspec_barshadow.rmap
Add explicit handling for N/A EXP_TYPEs.
> Updated NIRSPEC BARSHADOW spec

- crds/data_file.py
- crds/io/abstract.py
- crds/io/fits.py
for the catalog don't perform FITS checksums for each value.
> Refactored crds.io getval() so that server-side header value fetches

- documentation/crds_users_guide/source/reference_conventions.rst
to datamodels schema source code.
> Added description of P_ keywords and basic JWST conventions, link

- crds/core/selectors.py
Now reports on multiple bad keys/choices/sub-selectors rather than only the first found.
> Refactored core rmap selector validation 

- crds/jwst/tpns/nircam_all.tpn
- crds/jwst/tpns/nircam_all_ld.tpn
MASKA210R,MASKA335R,MASKA430R,MASKBSWB,MASKBLWB 
related to Jira CRDS-151.
> Added backward compatible values for NIRSPECDARK SUBARRAY

- crds/data_file.py
- crds/io/asdf.py
- crds/io/fits.py
- crds/io/geis.py
- crds/io/json.py
- crds/io/jwstdm.py
- crds/io/yaml.py
Typo in crds.sync log message.
> Modified checksum handling so general default is checksums off

- documentation/crds_users_guide/source/command_line_tools.rst
Removed extra empty "crds checksum" section.
> User's guide

- crds/client/api.py
> Added verbose output to include defined references as well as N/A

- crds/jwst/jwst_system_crdscfg_b7.1.1.yaml
- crds/jwst/pipeline.py
of v2v3 from expected reftypes for B7.1.1 and later.
> Added updated system crdscfg pseudo reference to capture the removal

- crds/tests/test_list.py
> Add catalog info to list cat

- crds/jwst/tpns/nirspec_coeffs_array.tpn
- crds/jwst/tpns/nirspec_dq_array.tpn
- crds/jwst/tpns/nirspec_linearity.tpn
- crds/jwst/tpns/nirspec_opt_err_array.tpn
- crds/jwst/tpns/nirspec_saturation.tpn
- crds/jwst/tpns/nirspec_sci_array.tpn
To handle GENERIC SUBARRAY references that are not full frame.
> Changed nirspec linearity and saturation constraints 

- crds/jwst/tpns/nirspec_dark.tpn
- crds/jwst/tpns/nirspec_linearity.tpn
- crds/jwst/tpns/nirspec_saturation.tpn
- crds/jwst/tpns/nirspec_superbias.tpn
for NIRSPEC DARK, LINEARITY, SUPEBIAS, SATURATION.
> Made GAINFACT a required parameter

- documentation/crds_users_guide/source/web_site_use.rst
> Update submit docs

- crds/core/heavy_client.py
> Tweaked log message for context selection for consistency with other

- crds/jwst/tpns/fgs_all.tpn
- crds/jwst/tpns/fgs_all_ld.tpn
- crds/jwst/tpns/miri_all.tpn
- crds/jwst/tpns/miri_all_ld.tpn
- crds/jwst/tpns/nircam_all.tpn
- crds/jwst/tpns/nircam_all_ld.tpn
- crds/jwst/tpns/niriss_all.tpn
- crds/jwst/tpns/niriss_all_ld.tpn
- crds/jwst/tpns/nirspec_all.tpn
- crds/jwst/tpns/nirspec_all_ld.tpn
relative to data models schema and jwst-reffiles documentation.
> Updated JWST tpn constraints

- crds/certify/validators.py
- crds/tests/test_certify.py
Customize missing keyword messages to specify missing table column when appropriate.
> Missing column

- crds/core/utils.py
into groups partitioned by (instrument, filekind).
> Added a utils function organize_files() to organize a list of files

- crds/certify/certify.py
- crds/core/log.py
- crds/jwst/locate.py
- crds/jwst/schema.py
- crds/tests/test_certify.py
- crds/tests/test_or_bars.py
Trivial error handling and output formatting changes to make crds list work better for files not yet in CRDS.
> Add fits keywords

- crds/io/asdf.py
> Updated ASDF history reader for change in format

- crds/bestrefs/headers.py
as described in Jira issue CCD-52.
> Fixes CCD-52 JWST repro dataset header fetch thrashing

- crds/certify/validators.py
Exposed duing delivery of ACS BPIXTAB described in Jira CCD-75.
> Bug-fix for CRDS certify Float validator

- CODE_OF_CONDUCT.md
CoC copied from https://github.com/spacetelescope/stsci-package-template/
> DOC: Add spacetelescope code of conduct

- crds/jwst/locate.py
Added HST-style behavior for attempt to create instrument directory in
readonly cache:  creation skipped with debug message.
> Added HST-style recovery for attempt to create instrument directory on

- setup.py
Command line scripts are not executing correctly with this import.
> Rolled back "import setuptools" again

- crds/hst/locate.py
- crds/jwst/locate.py
- crds/jwst/schema.py
- crds/list.py
- crds/tobs/locate.py
Adds crds list --check-exptypes for short term experimental analysis of EXP_TYPE coverage.
> Ccd 91 improve n/a handling

- crds/jwst/subarrays/SubarraysXML.xml
- crds/tests/test_certify.py
- setup_test_cache
> Update subarrays 2

- crds/__init__.py
- crds/core/git_version.py
> Updated git hash for 7.2.6 October baseline.

- crds/__init__.py
- crds/core/git_version.py
- setup.cfg
- setup.py
Kickoff for 7.2.8,  hopefully final branch of JWST B7.2.
> Started 7.2.8 branch.

- crds/io/asdf.py
> AsdfFile.open() deprecated.  Switch to asdf.open().

- setup.py
install_requires, tests_requires, package_requires.
> Added import setuptools to setup.py to suppress 3 warnings about:

- documentation/crds_users_guide/source/command_line_tools.rst
- documentation/crds_users_guide/source/web_site_use.rst
Changes in command line path hanlding to UNIX norms for pathless files vs. in-the-cache.
Minor improvements to discussion of batch submissions.
> Updated documentation 

- crds/core/utils.py
- crds/io/factory.py
- crds/io/yaml.py
- crds/jwst/gen_system_crdscfg.py
- crds/jwst/pipeline.py
- crds/submit/rc_submit.py
Switched all calls to yaml.load() to yaml.safe_load() due to known exploits for yaml.load().
> Switched to yaml.safe_load().

- documentation/crds_users_guide/source/conf.py
I noticed this was out of date...
> Set current year in copyright text

- crds/core/cmdline.py
- crds/submit/monitor.py
- crds/submit/rc_submit.py
- crds/submit/submit.py
- documentation/crds_users_guide/source/programmatic_interface.rst
https://jira.stsci.edu/browse/CCD-317
This changes the Submission.submit() method to return an object with fields that include the URL to the relevant review/confirm page.
> Return link to review/confirm page from Python API

- documentation/crds_users_guide/Makefile
- documentation/crds_users_guide/source/conf.py
Updated CRDS User's Guide Makefile based on JWST CAL documentation Makefile to add the "latex" and "latexpdf" rules among others.
> CCD-449 Create PDF of User's Guide

- scripts/crds_unique
Added script crds_unique for tweaking reference files so that they appear to be different than existing reference files.
> ccd-462 Add crds_unique to CRDS/scripts

- crds/__init__.py
- crds/core/git_version.py
- crds/core/pysh.py
- save_version
- setup.cfg
- setup.py
Updated version info for JWST DMS 7.3.3 release.
Overhauled crds.core.pysh and save_version due to incompatibilities with recently added shlex quoting.   Added handling for multi-word commands to pysh API routines.
> Updated release version; save_version + pysh fixes needed

- crds/hst/locate.py
Improve error handling for bad HST instrument or filetype specification.
> Ccd 506 missing instrume

- documentation/crds_users_guide/source/file_submissions.rst
> Consolidated documentation for submit mappings

- crds/tests/test_certify.py
- crds/tests/test_or_bars.py
For changes in CAL datamodels warnings format.   CCD-510
> Update unit tests

- crds/core/heavy_client.py
> Fixed CRDS_MODE=remote

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/miri_pars-refpixstep.rmap
> Ccd 551 Add new reftype `pars-refpixstep`

- crds/certify/certify.py
- crds/certify/mapping_parser.py
- crds/diff.py
- crds/jwst/locate.py
- crds/list.py
- crds/misc/get_synphot.py
- crds/refactoring/checksum.py
- crds/refactoring/newcontext.py
- crds/refactoring/refactor2.py
- crds/sync.py
- crds/tobs/locate.py
rmap.is_mapping   -->  config.is_mapping
rmap.locate_reference  --> config.locate_reference
rmap.locate_mapping --> config.locate_mapping
rmap.locate_file --> config.locate_file
rmap.mapping_exists --> config.mapping_exists
> For CCD-562 updated obsolete imports

- crds/core/config.py
- crds/core/heavy_client.py
- crds/core/rmap.py
- setup.py
Here's an approach to streaming mappings/references
> Implement streaming from S3

- crds/core/log.py
- crds/diff.py
- crds/io/abstract.py
- crds/jwst/locate.py
- crds/list.py
- crds/rowdiff.py
- crds_setup_env
So that lightweight aspects of CRDS can run without it being installed.
Adjusted crds_setup_env for batch installation.
Added jwst.locate.disable_fits_annotations(),
> Deferred imports of astropy

- crds/jwst/tpns/all_photom.tpn
After discussion with PH,  believe now handled by AREA.
> Completely removed PHOTOM PIXAR_xxx warnings

- crds/__init__.py
- crds/core/git_version.py
After discussion with PH,  believe now handled by AREA.
> Updated 7.4.1.2 githash

- crds/list.py
- crds/tests/test_list.py
- update_version_and_tag
Added update_version_and_tag script for automating the process of doing formal release tagging.
Added CRDS Summary section to crds list --status to show __rationale__.
Updated unit test.
> Added update_version_and_tag script

- crds/hst/specs/cos_tdstab.spec
- crds/hst/tpns/cos_tds.tpn
- crds/hst/tpns/cos_tds_ld.tpn
... to drop CENWAVE from header checks and add CENWAVE to unique row keys.
> Update COS TDSTAB

- crds/hst/tpns/acs_ccd.tpn
- crds/tests/test_certify.py
Addresses https://jira.stsci.edu/browse/CCD-642
> Add OVRHFLS and OVRHUFLS to ACS CCDTAB

- crds/__init__.py
- crds/core/git_version.py
- crds/hst/tpns/acs_ccd.tpn
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/nircam_apcorr.rmap
- crds/jwst/specs/nirspec_apcorr.rmap
- crds/jwst/tpns/includes/apcorr.tpn
- crds/jwst/tpns/miri_rscd.tpn
- crds/jwst/tpns/nircam_apcorr.tpn
- crds/jwst/tpns/niriss_apcorr.tpn
- crds/jwst/tpns/nirspec_apcorr.tpn
- setup.cfg
- setup.py
Resolves [CCD-666](https://jira.stsci.edu/browse/CCD-666)
WIP [CCD-650](https://jira.stsci.edu/browse/CCD-650)
Note: Inclusion here was unintentional, but this will implement everything. Only the NIRSpec version has not been tested, but we'll leave that for test. The files related here were in PR #736, which has been approved. That PR will simply be removed in favor of this one.
> CCD 666 Support redefined RSCD reference files

- crds/jwst/tpns/nirspec_apcorr.tpn
Enables CRDS-338
Resolves CCD-650
> Update NIRSpec APCORR tpn to actual.

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/nircam_filteroffset.rmap
Resolves [CCD-665](https://jira.stsci.edu/browse/CCD-665)
> Add spec for NIRCam FILTEROFFSET

- crds/certify/certify.py
- crds/tests/test_certify.py
Just something I noticed fly by in the logs
> Fix typo (betwween --> between)

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/fgs_abvegaoffset.rmap
- crds/jwst/specs/miri_abvegaoffset.rmap
- crds/jwst/specs/nircam_abvegaoffset.rmap
- crds/jwst/specs/niriss_abvegaoffset.rmap
Resolves [CCD-669](https://jira.stsci.edu/browse/CCD-669)
> Add ABVEGAOFFSET specs

- crds/tests/test_reftypes.py
Just a little missing detail...
> Add 'abvegaoffset' to list of reftypes in test

- crds/misc/get_synphot.py
At present the get_synphot command is completely broken.   This fixes it.
> Fix for refactoring error in get_synphot.

- crds/certify/validators/helpers.py
- crds/jwst/tpns/nirspec_all.tpn
> CCD-737 Add NRS_VERIFY to EXP_TYPE for validity checking

- crds/roman/locate.py
- crds/roman/specs/combined_specs.json
- crds/roman/specs/wfi_flat.rmap
- crds/roman/tpns/wfi_all.tpn
- crds/roman/tpns/wfi_flat.tpn
This adds support for the Roman FLAT reference file type.
> Add support for Roman FLAT reference type

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/nirspec_apcorr.rmap
Resolves [CCD-891](https://jira.stsci.edu/browse/CCD-891)
> CCD-891 Update nirspec apcorr spec to include filter and grating as parkeys

- crds/core/config.py
Opening this PR to invoke the tests...
> Recognize GEIS data files as references

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/fgs_pars-tweakregstep.rmap
- crds/jwst/specs/nircam_pars-tweakregstep.rmap
- crds/jwst/specs/niriss_pars-tweakregstep.rmap
- crds/jwst/specs/nirspec_cubepar.rmap
- crds/jwst/tpns/nirspec_all.tpn
- crds/tests/test_reftypes.py
WIP [CRDS-401](https://jira.stsci.edu/browse/CRDS-401)
To fix unit tests, rmap specs for various instrument `pars-tweakregstep` have been added.
> CRDS-401 add LAMP_MODE to the CUBEPAR PARKEYS

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/fgs_pars-outlierdetectionstep.rmap
- crds/jwst/specs/fgs_pars-sourcecatalogstep.rmap
- crds/jwst/specs/miri_pars-outlierdetectionstep.rmap
- crds/jwst/specs/miri_pars-sourcecatalogstep.rmap
- crds/jwst/specs/nircam_pars-outlierdetectionstep.rmap
- crds/jwst/specs/nircam_pars-sourcecatalogstep.rmap
- crds/jwst/specs/niriss_pars-outlierdetectionstep.rmap
- crds/jwst/specs/niriss_pars-sourcecatalogstep.rmap
- crds/tests/test_reftypes.py
Resolves CCD-908/CCD-909
Defines specs for the `pars-outlierdetectionstep` and `pars-sourcecatalogstep`
> CCD-908/CCD-909 pars-outlierdetectionstep and pars-sourcecatalogstep specs

- crds/jwst/tpns/nirspec_cubepar.tpn
Resolvess [CCD-919](https://jira.stsci.edu/browse/CCD-919)
> CCD-919 Update nirspec cubepars tpn for calibration exposures

- crds/hst/specs/acs_satufile.rmap
- crds/hst/specs/combined_specs.json
I forgot to update the HST combined_specs.json when I added CCDAMP to the ACS SATUFILE...
> Update HST combined_specs.json

- TESTING
- clean
- documentation/crds_users_guide/Makefile
I noticed these while I was cruising around.  They don't appear to be impacting anything...
> Update a few overlooked references to the sources directory

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/niriss_speckernel.rmap
- crds/jwst/specs/niriss_specprofile.rmap
- crds/jwst/specs/niriss_spectrace.rmap
- crds/jwst/specs/niriss_wavemap.rmap
- crds/tests/test_reftypes.py
Resolves CCD-[967](https://jira.stsci.edu/browse/CCD-967)/[968](https://jira.stsci.edu/browse/CCD-968)/[969](https://jira.stsci.edu/browse/CCD-969)/[970](https://jira.stsci.edu/browse/CCD-970)
WIP [CRDS-388](https://jira.stsci.edu/browse/CRDS-388) and all subtasks
> CRDS-388 New NIRISS SOSS extract_1d reference files

- crds/tests/test_roman.py
Added a test for Roman SOC-628.1
> add test for Roman 628

- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/niriss_distortion.rmap
> Update NIRISS distortion spec for new parkeys

- CHANGES.rst
- changelog.yml
- crds/jwst/locate.py
- crds/tests/test_certify.py
This also adds a CHANGES.rst and GitHub actions workflow to help maintain it.
> Show all JWST datamodels validation failures

- CHANGES.rst
- documentation/README.rst
- documentation/crds_users_guide/Makefile
- documentation/crds_users_guide/source/programmatic_interface.rst
> CCD-1082 Update documentation for the Submission API

- CHANGES.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/miri_pathloss.rmap
Resolves [CCD-1091](https://jira.stsci.edu/browse/CCD-1091)
> CCD-1091 Update miri pathloss spec

- .github/workflows/ci.yml
- CHANGES.rst
- setup.py
- Update minimum python to 3.8.
- remove 3.7 and add 3.9 to CI
> Update minimum python to 3.8

- CHANGES.rst
- crds/submit/rc_submit.py
Resolves [CCD-1118](https://jira.stsci.edu/browse/CCD-1118)
Though this should have been completed in #856, that PR was incomplete. This finishes the task.
> CCD-1118 Add pub to the possible submission groups.

- CHANGES.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/miri_mrsptcorr.rmap
- crds/jwst/tpns/miri_mrsptcorr.tpn
Resolves [CCD-1168](https://jira.stsci.edu/browse/CCD-1168)
> CCD-1168 Create new reftype mrsptcorr

- CHANGES.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/nirspec_sflat.rmap
Resolves [CCD-1209](https://jira.stsci.edu/browse/CCD-1209)
> CCD-1209 Add LAMP_MODE and LAMP_STATE to NIRSpec SFLAT spec

- CHANGES.rst
- crds/submit/rc_submit.py
- crds/submit/submit.py
- install
File submission object includes 'file_map' dictionary attribute of uploaded and renamed filenames.
> ccd-1194-submission-api-filemap

- CHANGES.rst
- README.rst
resolves [SCSB-44](https://jira.stsci.edu/browse/SCSB-44)
@nden
> change reference from `astroconda` to `stenv`

- CHANGES.rst
- crds/sync.py
> Add 'delivered' as an allowed state for crds sync

- .gitignore
- CHANGES.rst
exclude build/ and install.log from source control
> gitignore-update

- CHANGES.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/miri_filteroffset.rmap
> CCD-1227 Add subarray to the miri filteroffset spec

- CHANGES.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/miri_pars-jumpstep.rmap
Update parkeys for MIRI pars-jumpstep
> CCD-1260 Update miri pars-jumpstep parkeys

- CHANGES.rst
- documentation/crds_users_guide/source/file_submissions.rst
> Change references to ICD47 in crds user guide

- CHANGES.rst
- crds/hst/specs/combined_specs.json
- crds/hst/specs/wfc3_satufile.rmap
- crds/hst/tpns/wfc3_sat.tpn
- crds/hst/tpns/wfc3_sat_ld.tpn
Added new WFC3 SATUFILE reference file type
> HST/WFC3: Added new WFC3 SATUFILE reference file type (CRDS-691)

- test/test_list.py
- test/tobs/test_list.py
This is not an official merge request yet, it's more to test the changes I am making to see if the checks will succeed. When they are succeeding I will request a review, but I expect to have to make numerous commits.
> Attempting fixes for list.py CI checks.

- pyproject.toml
- test/test_bad_files.py
- test/test_list.py
Got tests working for bad_files, though expecting some failures since I don't think my container setup is identical to Ru's, and we seem to be getting different results when tests are run.
> Converted bad_files to pytest.

- pyproject.toml
- test/test_rowdiff.py
This PR migrates the test_rowdiff module from doctests to functional tests.
> CCD-1347 migrate rowdiff tests

- pyproject.toml
- test/bestrefs/test_bestrefs.py
- test/refactoring/test_refactor.py
crds.refactoring.refactor tests converted to pytest
> refactoring.refactor tests

- pyproject.toml
- test/bestrefs/test_table_effects.py
- test/refactoring/test_checksum.py
Convert the module test_table_effects to pytest-ready tests.
> CCD-1354 Convert table-effects tests

- pyproject.toml
- test/misc/test_uniqname.py
Migrate test_uniqname to pytest-compatible functions
> CCD-1355 Migrate test_uniqname to pytest-compatible functions

- pyproject.toml
- test/test_uses.py
Convert test_uses module to pytest
> CCD-1356 convert test_uses module to pytest

- conftest.py
- pyproject.toml
- test/test_sync.py
Many of the tests for test_sync.py converted rather easily, but I do notice that some tests are not running exactly the same way each time. I imagine it has to do with the set up I'm using, so hopefully that can be solved.
> Converted tests for test_sync.py

- .github/workflows/ci.yml
- pyproject.toml
- runtests
~runs tests in parallel with `pytest-xdist`,~ add `workflow_dispatch` to `ci.yml` for manually starting tests, and also a `concurrency` block to manage multiple pushes to the same branch
> various minor improvements to CI

- CHANGES.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/miri_gain.rmap
- crds/jwst/specs/miri_pars-detector1pipeline.rmap
Added BAND to miri_gain and DETECTOR to miri_pars-detector1pipeline spec files.
> (CCD-1376 and CCD-1377) Added BAND to miri_gain and DETECTOR to miri_pars-detector1pipeline spec files. 

- CHANGES.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/miri_emicorr.rmap
- crds/jwst/tpns/miri_emicorr.tpn
Added a new rmap following guidelines presented in CCD-1386.
> (CCD-1386) Created new rmap for miri_emicorr.

- CHANGES.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/miri_emicorr.rmap
Suffix needed to be fixed as well.
> Updated rmap for miri_emicorr.

- CHANGES.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/niriss_nrm.rmap
- crds/jwst/specs/niriss_pars-whitelightstep.rmap
Needed to add a new rmap for niriss_pars-whitelightstep. Planning to make a release when this is merged.
> CCD-1422 New rmap for niriss_pars-whitelightstep.rmap

- crds/jwst/locate.py
- crds/tobs/locate.py
closes #1040 
This PR addresses issues raised by SonarQube at https://plsonarqube.stsci.edu/project/issues?resolved=false&types=BUG&inNewCodePeriod=false&id=crds_client
> fix SonarQube issues

- crds/client/api.py
This merge request attempts to resolve CCD-1497, so that we may obtain the jwst cal version and then use it to select a default context, likely through a table lookup (coming later).
api.py was also reformatted for pep-8 standards, double spacing functions and adjusting character spacing. The main function added is on line 242.
> Obtain JWST Cal Version.

- documentation/crds_users_guide/source/web_site_use.rst
Resolves [CCD-nnnn](https://jira.stsci.edu/browse/CCD-nnnn)
Closes #
This PR addresses ...
</details>
> Updated image names.

- documentation/crds_users_guide/source/conf.py
> remove `display_version` from docs config

- changes/1120.jwst.rst
- crds/jwst/specs/combined_specs.json
- crds/jwst/specs/niriss_bkg.rmap
- crds/jwst/specs/niriss_sirskernel.rmap
- crds/jwst/specs/nirspec_pictureframe.rmap
- crds/jwst/specs/nirspec_sirskernel.rmap
Resolves [CCD-1567](https://jira.stsci.edu/browse/CCD-1567)
> Updated description values for multiple rmaps.
