crds/jwst/locate.py
CRDS was generating files paths with uppercase instrument names for the default "instrument" organization for JWST.    Modified to squash instrument name to lower case.
=> Fix for DR-003136 mixed case paths dont work

crds/certify.py, crds/jwst/specs/all_dark.spec, crds/jwst/tpns/all_dark.tpn, crds/jwst/tpns/all_dark_ld.tpn, crds/reftypes.py
Added capability to define constraints across all instruments for a filekind via one .tpn
Added capability to define NOT_ values which are disallowed..
Defined JWST SUBARRAY=GENERIC as disallowed for all DARKs.
=> crds.certify changes to constrain SUBARRAY=GENERIC disallowed for all DARK types

crds/jwst/locate.py
keywords with the assumption that the translations are context insensitive
as is implied by the current call interface but not really required by
DM schema declarations.  (*huge* optimization for reprocessing bestrefs.)
=> Cached JWST fits_to_parkey translation from non-DM keywords to DM

TESTING, crds/tests/test_bestrefs.py, crds/tests/test_config.py, crds/tests/test_diff.py, crds/tests/test_rmap.py, crds/tests/test_uses.py, crds/tobs/tests.py, runtests
This is the beginning of testing consolidation that will attempt to reduce custom test caches and dependence on /grp/crds/cache for unit testing with the hope of using Travis CI for the CRDS client library. This change set merely renames the custom testing support cache so that it doesn't have an identical name to the user cache nominally used with the TEST servers.
=> Testing consolidation

crds/certify.py
Made crds.certify check for USEAFTER format stricter for JWST,  limiting formats to:
YYYY-MM-DDTHH:MM:SS
YYYY-MM-DD  (with assumed T00:00:00)
=> Jwst useafter format error

crds/__init__.py, crds/bestrefs.py, crds/certify.py, crds/client/api.py, crds/cmdline.py, crds/config.py, crds/diff.py, crds/heavy_client.py, crds/hst/locate.py, crds/jwst/schema.py, crds/list.py, crds/matches.py, crds/newcontext.py, crds/refactor2.py, crds/rmap.py, crds/sync.py, crds/uses.py, crds/utils.py
Added features for optionally using pickled CRDS contexts rather than loading .pmaps and all their descendant mappings.   Currently these default "off" but can be enabled by setting environment variables (as-is done on the CRDS servers).   Potentially these can benefit the archive pipeline client bestrefs as well by avoiding concurrent context loads from multiple processes of context trees.
=> Auto pickling 2

crds/heavy_client.py
Within the memory cached get_pickled_mapping() function,  the context load for the case with no pickle or failed pickles must use memory caching so that they're incremental during iterations over all contexts.  Unlike get_pickled_mapping() which memory caches only at the top level,  get_cached_mapping() (or asmapping with cached=True) caches each loaded sub-mapping as well;  this is critical to prevent re-loads when iterating over all contexts.
=> Critical pickling bug-fix,  interior caching

crds/jwst/tpns/all_dark.tpn
…with the caveat that
submitted references can only be applied to matching data.
=> Removed .tpn value restrictions on JWST all_dark NFRAMES and GROUPGAP

crds/timestamp.py
and elimination of optional time.  (making full datetime required).
=> Corrected CRDS unit test following formal USEAFTER format definition

crds/sync.py
to achieve simple "stick all the files here" behavior.  CRDS has more
granulated configuration controlled by env vars but this is convenient
for quick command line use and obtaining arbitrary files "right here"
instead of off buried in a CRDS cache.
=> Added simple --output-dir switch to crds.sync to jam config env vars

crds/jwst/specs/miri_rscd.rmap
correctly auto-update with USEAFTER support when adding new references.
=> Added 'classes' field to MIRI RSCD spec/baseline rmap so that it will

crds/jwst/specs/miri_rscd.rmap, crds/jwst/specs/system_calver.rmap
Added META.OBSERVATION.DATE + META.OBSERVATION.TIME keywords to MIRI RSCD and SYSTEM CALVER spec parkey header field corresponding to USEAFTER lookup.
=> Update MIRI RSCD and SYSTEM CALVER specs for USEAFTER

crds/tests/test_diff.py
Removes path-only differences from cache-to-cache comparisons.
=> Updated unit tests for cache-to-cache diff output simplification.

crds/bestrefs.py, crds/certify.py, crds/client/api.py, crds/cmdline.py, crds/diff.py, crds/heavy_client.py, crds/hst/locate.py, crds/jwst/schema.py, crds/list.py, crds/matches.py, crds/newcontext.py, crds/refactor2.py, crds/sync.py, crds/uses.py
Reverted instances of get_pickled_mapping() inside loops over context to get_cached_mapping() because the latter is more memory efficient and roughly equivalent once the bulk of the mappings network is loaded.   Marked those instances of get_pickled_mapping() which appeared loop-free as "reviewed".
=> More pickling memory consumption reversions

crds/client/proxy.py
Added additional information to JSONRPC ids to make it easier to track requests and responses by program name, unique process identifier, CRDS version, and request id.  The end result is to identify where particular message patterns are coming from in the Apache logs.
=> Enhanced rpc ids

crds/hst/specs/combined_specs.json, crds/jwst/specs/combined_specs.json, crds/reftypes.py, crds/tobs/specs/combined_specs.json
OS-X and Linux were producing different results for the combined type spec .json formatting. The scheme requires continually rewriting the specs to avoid forgetting it when adding new types.  Adding explicit separators parameter to dumps() eliminated platform specific white space so both Linux and OS-X rewrite the same spec... hence it doesn't change just because of platform,  only when the individual specs change.
=> Added explicit separators to combined spec .json dump 

crds/heavy_client.py
Improve the message issued when both the CRDS_SERVER_URL and CRDS_PATH are unworkable.
=> Improved the "Cannot continue" message

crds/heavy_client.py, crds/sync.py
Changed crds.sync so that it does not rewrite existing context pickles unless --clear-pickles is set in addition to --save-pickles.
Added INFO messages for context pickle saves and loads so that when the automatic machinery is running is obvious and less of a hidden variable.
Mostly affects CRDS servers where pickles are used by default.
=> Limit and expose when context pickles are (re)written

crds/client/api.py, crds/tests/test_certify.py, crds/tests/test_heavy_client.py, crds/tests/test_rmap.py
prior to raising a single exception for *some* reference at the end.
This supports more effectively iterating with the pipeline on
reference file coverage since it should enable the cal code to report
on all missing references (CRDS knows about, running in the pipeline)
at the same time rather than via a cascade of type-by-type debug
sessions.  Added a test for this which unfortunately is not working
correctly for the two error messages that are the entire point of the
change.   AFAICT it's the test not the code.
Removed one chronically failing certify test for "unknown" reference
types which I don't think will ever be "fixed".
Removed an asymmetric (unclosed) call to test_config.setup() in
test_rmap.py...  there should be a test_config.cleanup() or else no
calls to test_config.
=> Modified api.cache_references() to issue errors for each bad reference

crds/hst/locate.py, crds/jwst/locate.py, crds/newcontext.py, crds/rmap.py
notation used to set values to N/A.
Normally crds.newcontext takes an existing pmap and a list of new
rmaps to inject in order to create a new pmap and related imaps.  With
this enhancement, one can also specify e.g. miri_dflat_n/a and
newcontext will set the MIRI DFLAT value to N/A instead of an
rmap.
=> Enhanced newcontext script and functions to support a pseudo-rmap

crds/rmap.py
ReferenceMapping.difference() method was missing new recurse_replacements parameter.
=> Bugfix for missing recurse_replacements

crds/config.py
Added "versions" as a kind of default context that can be queried,  nominally
this is the last defined context,   or more ideally,  the last context
in which SYSTEM CALVER changed.   This is not necessarily the context in use
in the pipeline,  or the context from which future rules are derived.   This
is the context that reflects the monotonically increasing ability of CRDS to
interpret cal code master version numbers into a component version reference
file.   So even when say the calibration references temporarily revert to an
old version of CRDS rules,  the ability of CRDS to interpret version strings
should not correspondingly revert;   that would couple reversions in the cal
code as well and generally those do not occur.   This is a regex change making the -versions 
decoration legal, …
=> Accept "versions" defaut context specifier

crds/diff.py, crds/rmap.py
Removed the feature for limiting mapping differences to the current mapping,  short-circuiting recursion.  Too complicated relative to usefulness.
=> Undo recurse diffs

crds/jwst/specs/combined_specs.json
Files in the project "specs" directory are now loaded and combined into combined_specs.json files that are generated automatically by running ./install and then committed to the code base.   This is a file count i/o optimization needed due to Isilon performance issues that exaggerate the cost of every file open.
=> Generated new JWST combined_specs.json including msa and pathloss specs.

crds/config.py, crds/heavy_client.py, crds/list.py, crds/sync.py
Switched to uncached version of get_pickled_mapping() in crds.sync --save-pickles method,  simplified method, simplified config.locate_pickle() to automatically add ".pkl" suffix and refactored all calls.
=> Reduced crds.sync --save-pickles memory utilization

documentation/crds_users_guide/source/web_services.rst
Clarified acceptable dataset ID counts for JSON RPC calls in user's guide., AUI bestrefs interface.
=> User's guide update for AUI JSONRPC

crds/jwst/specs/combined_specs.json, crds/jwst/specs/niriss_specwcs.rmap, install
Updated NIRISS SPECWCS baseline rmap to include:
"reference_to_dataset" header  field for rmap update translations from ASDF tree names to data model names.
"substitutions" header field to define run time substitution from GENERIC to N/A.
EXP_TYPE's defined explicitly as N/A to support data driven operation of assign_wcs, skipped processing.
=> Add NIRISS SPECWCS N/A EXP_TYPE's

crds/cmdline.py, crds/heavy_client.py, crds/jwst/pipeline.py, crds/tests/test_bestrefs.py
Fix for JWST header_to_reftypes EXP_TYPE determination,  new default of [] (all types) when determination fails.   
Improved unique errors mixin by adding count of untracked errors to summary
=> Centralize pipeline awareness

crds/exceptions.py, crds/heavy_client.py, crds/jwst/pipeline.py, crds/tests/test_bestrefs.py, crds/tests/test_heavy_client.py
Overhauled JWST pipeline .cfg + reftype determination fixing issues with missing FLAT types.
Added JWST pipeline support for NRS_CONFIRM.
Made reftypes determination failure a normal warning instead of a verbose warning.
Simplified getreferences() CRDS environment dump for more succinct typical pipeline usage.
=> Jwst flat type determination

crds/selectors.py
Fixes replacement of rmap matching values of GENERIC with N/A.   Bug intermittent,
limited to rmaps which use "substitutions" and witnessed for Python-3 only during reprocessing regressions.
=> Bugfix for dictionary mutation during iteration in substitution code

crds/jwst/locate.py, crds/timestamp.py
Modified CRDS to support USEAFTER values without time once again.   Also switched to support fetching USEAFTER from data model META.REFFILE.USEAFTER.
=> Datamodel useafter workaround

crds/bestrefs.py
Added --drop-ids to crds.bestrefs to support weeding out datasets that are still represented in the archive parameter service but have been dropped from a build as test cases and are known failures.
=> Add bestrefs drop list

.travis.yml, crds/tests/test_certify.py
Tweaked certify truncation test,  should work on Travis,  not locally due to doctest output variance.
Removed coveralls from .travis.yml due to frequent false failures.
=> Testing changes

crds/core/exceptions.py, crds/refactoring/refactor.py
Added better logging and exception messages for case where one or more references in an rmap update have identical matching criteria and overwrite one another.   The overwrite results in some of the submitted files not appearing in the new rmap.   This update identifies both conflicting file names in the exception message.   The command line tool can also identify all conflicts in a series of references before raising a final fatal exception.
=> Improved diagnostic messages for rmap updates

crds/misc/check_archive.py, crds/submit/web.py
Failed 3rd party imports (requests, lxml) for non-essential tools (submit, check_archive) don't obstruct basic CRDS functions.
=> Softened imports of requests and lxml modules

crds/hst/locate.py, crds/misc/uniqname.py
This change adds support for TMC, TMG, and TMT synphot files to the HST package and crds.uniqname.   Support is superficial,  restricted to generating new file names.
=> Add synphot to uniqname

crds/core/exceptions.py, crds/core/selectors.py, crds/core/timestamp.py
Handles common error case where 1/2 of required date/time keywords is left undefined and the other contains all of date/time.
=> Improves invalid date/time diagnostics

scripts/crds
Issues help when only two words are specified on the command line,  e.g.
% crds list
is now equivalent to crds list --help
=> Tweaked crds wrapper script

crds/core/heavy_client.py, crds/core/rmap.py
Reordered hv_best_references() to condition header parameters before calling project specific header_to_reftypes.   Limited requested types to the types actually supplied in a context,  possibly fewer than those recommended by the EXP_TYPE and Step config files.   This logic applies only to the case where the specified reftypes (include parameter) is left defaulted as None;  for that case,  CRDS attempts to figure out the  complete set of appropriate references based on both the context and CRDS knowledge of applicable Steps and their references.
=> Fix determine reftypes

crds/core/rmap.py, crds/diff.py
Nominally this occurs in cache-to-cache differences where filepaths are different but mapping contents are the same.  Used sha1sum of loaded mapping to identify files.
Also improved crds diff --help to suggest the best switches for normal use,  not defaults due to the evolution diff and backward compatibility.  The defaults can probably be simplified.
=> Modified crds diff (rmap code) to ignore differences solely due to file paths

crds/__init__.py
=> Filtered out the import warning related to the complex CRDS __init__

crds/client/api.py, crds/core/pysh.py, crds/list.py
Modified crds.list to support dumping unlimited numbers of dataset IDs.   This entailed supporting @-file syntax on the command line to exceed UNIX command line word limits as well as adding an API call that implicitly loops around more primitive fixed-block-length header reads.
As an unrelated commit,  added lightweight arg() function to crds.core.pysh to support trivial command line parameter handling for *hitty little scripts that don't rate argparse.
=> List all datasets

crds/core/cmdline.py, crds/list.py
Abstracted as get_words() so it can be used for dataset ids without the assumption that filenames are being determined.
=> Refactored command line get_files() method used to support @-files

crds/certify/certify.py, documentation/crds_users_guide/source/command_line_tools.rst
CRDS normally assumes rules and references are in the CRDS cache.   To specify files in the current working directory,  ./ or an absolute path must be used.   (This is a questionable design decision that may have to be reversed,  omitting ./ is a very common mistake.)
=> Updated documentation for certify (and --help) about ./

crds/rowdiff.py
Web display gives gentler indication and still produces header diffs.
=> Trapped rowdiff runtime error for inconsistent hdus

crds/tests/test_bestrefs.py
running on contexts that did not support that.
=> Fix for unit test broken by new datasets with COS LIFE_ADJ=4

.travis.yml, crds/jwst/locate.py, crds/tests/test_certify.py, runtests
Updates to .travis.yml to rely solely on conda-dev.  Package dependency pinning simplifications.
Added support for JWST P_GRATING pattern keyword.
Updated several doctests.
Attempted to add correct exit status to ./runtests, apparently still broken.   This means Travis CI results have to be inspected even on seemingly successful runs.
=> Misc post locking

crds/__init__.py
conflicts with the CRDS server version number obscuring the client version.
=> Switched back to hard coded __version__ since the pkg_resources version

crds/io/abstract.py
No point in cross-strapping a keyword to itself.
=> Eliminated redundant io keyword cross-strap

crds/core/config.py
Reviewed and reactivated a number of by-instrument parameter constraints that are stricter than the data models.  Bugfix for CRDS cache locking acquiring/acquired log messages.
=> Fix for is_simple_mapping() when called with loaded mapping object.

crds/bestrefs/bestrefs.py, crds/core/heavy_client.py, crds/core/selectors.py, crds/hst/locate.py, crds/jwst/jwst_system_crdscfg.yaml, crds/jwst/pipeline.py, crds/jwst/specs/combined_specs.json, crds/jwst/specs/system_crdscfg.rmap, crds/tests/test_bestrefs.py, crds/tobs/locate.py
Modified crds.jwst.pipeline module (determines required types for reprocessing w/o running cal code.) to operate via a system crdscfg reference file.   This is still prospective code, the necessary rmap and initial reference are not yet delivered.   An alternative approach would be to generate rmap relevance expressions for all rmaps based on these inputs and then maintain rmaps later rather than this consolidated reference.    Retaining B7 reprocessing  behavior with old contexts probably/does require retaining the initial builtin default form of this reference file.
=> Refactor pipeline

crds/core/selectors.py
Made the default class nesting:
Match
UseAfter
so that the "classes" rmap header directive is no longer required for the now nominal JWST case.
=> Changed default rmap structure for JWST

crds/bestrefs/bestrefs.py, crds/tests/test_special.py
Changed log error messages of form <id:id> to <id>.  This is mainly for JWST but applies to any unassociated parameter set.
=> Modified bestrefs to simplify ID output 

crds/refactoring/checksum.py
enabling debugging flawed typespecs that wont even checksum.
=> Migrated crds.checksum tool to standard CRDS command line tool format

crds/core/selectors.py
Modified the rmap substitutions logic used to implement SUBARRAY=GENERIC to provide for default substitutions since the translation for GENERIC to N/A is frequently forgotten when SUBARRAY is added as a matching parameter.
=> Add default substitutions

crds/core/selectors.py, crds/jwst/locate.py, crds/jwst/pipeline.py
CRDS for JWST raises exceptions when multiple rmap cases match the same parameter set with the same weight.   This mod makes crds.certify issue warnings for JWST when it sees overlapping cases in an rmap.  
For HST overlaps can be detected by adding --verbose to crds.certify.   
For JWST no --verbose is needed.  For HST overlaps are dynamically merged by default.   For JWST overlaps encountered at runtime result in an exception by default.
Overt warnings and exceptions can be avoided by adding "merge_overlaps" : "True" to the rmap's header.   However,  it is better to address the warnings by eliminating overlaps:
1.  Try to combine the overlapping cases,  perhaps broadening or narrowing the scope of files.
2.  Remove obsolete files and corresponding cases.
=> Improve jwst overlap warning

crds/bestrefs/bestrefs.py
Also specifying --update-pickle causes CRDS to save error results as well as good results so that all results can be compared during regression testing.    For ordinary bestrefs,  CRDS does not update reference file keywords where an error occurs.
=> Modified behavior of crds.bestrefs --save-pickle for regression capture

crds/__init__.py, crds/bestrefs/bestrefs.py, crds/bestrefs/headers.py, crds/bestrefs/table_effects.py, crds/client/api.py, crds/client/proxy.py, crds/core/cmdline.py, crds/core/heavy_client.py, crds/core/mapping_verifier.py, crds/core/naming.py, crds/core/rmap.py, crds/core/selectors.py, crds/core/substitutions.py, crds/core/timestamp.py, crds/core/utils.py
This refactoring continues the partitioning of the CRDS package into sub-packages,  primarily by making the mutual imports for the crds.core package relative and more self-contained,  reducing and eliminating circularities.   It does not directly address functional problems,  it is intended to preempt future problems by simplifying the import graph.   It is partial solution,  but a step in the right direction.  (Unfortunately crds.__init__ is still a kitchen sink import.  But this may facilitate eventually fixing that.)
=> Refactor imports

crds/core/heavy_client.py
return value not implemented/used correctly.   
Addresses mysterious problems with CRDS doing str(meta.wcs) and crashing deep down in a numpydoc/sphinx related module import.  Removes non-simple objects like meta.wcs as intended,  it's not used for matching.
=> Bugfix for heavy_client.check_parameters() header screening function

crds/__init__.py, crds/core/cmdline.py, crds/core/heavy_client.py, crds/jwst/schema.py, crds/list.py, crds/tests/test_heavy_client.py
One stop shopping for CRDS context definition vs. multiple input forms like CRDS_CONTEXT.
=> Added cleaner heavy_client.get_context_name() function

crds/hst/locate.py, crds/jwst/jwst_system_crdscfg_b7.1.yaml, crds/jwst/pipeline.py, crds/list.py, crds/tests/test_list.py
Remapped NIS_FOCUS to calwebb_image2.cfg  
Regenerated from latest JWST CAL code,  picking up support for WAVECORR and gain_scale.
Added --expected-reftypes and --expected-pipelines to crds.list to dump these results.
Added additional related placeholder plugin functions to crds.hst.locate
=> Updated system crdscfg for b7.1

crds/core/selectors.py, crds/tests/test_or_bars.py
Consistent ordering of or-glob values is required to do literal substitutions in rmaps, this change causes equivalent or-globs to retain the order already in the rmap so that new entries with equivalent globs augment what is already there rather than creating an overlapping case.
=> Modified or-bar handling to sort reference file values

crds/jwst/tpns/fgs_flat.tpn, crds/jwst/tpns/fgs_mask.tpn, crds/jwst/tpns/nir_dq_array.tpn, crds/jwst/tpns/nir_dq_irs2_array.tpn, crds/jwst/tpns/nir_err_array.tpn, crds/jwst/tpns/nir_sci_array.tpn, crds/jwst/tpns/nir_subarray.tpn, crds/jwst/tpns/nirspec_err_array.tpn, crds/jwst/tpns/nirspec_sci_array.tpn
FGS_ID-STACK references.
Relaxed NIR array checks to handle SUBARRAY references that use stripes
instead of exact matches to SUBARRAY keyword dims.
Removed array checks on FGS flat and mask pending a new solution for FGS_ID-STACK.
=> Updated JWST tpns to remove conditional XDIM constraint added to support

crds/bestrefs/bestrefs.py, crds/core/selectors.py, crds/tests/test_table_effects.py
Added progress messages every 1000 datasets at verbosity=5
Modified selectors.py to issue UseAfter merge debug output at verbosity=10.
Updated unit tests affected by additional debug output.
=> Enhanced crds.bestrefs log output

crds/client/api.py, crds/list.py, scripts/crds_dataset_capture
Modified crds.list to avoid N^2 algorithm caused by differences between 'requested' and 'returned' IDs which can expand to include all exposures for a product;  now just operates on returned ids.
Added crds_datasets_capture script to automate crds.list dumps more without totally rewriting.
Modified client API to generate headers rather than return massive dictionaries.
=> Improved crds.list matching parameter capture

.travis.yml, crds/core/config.py, crds/core/crds_cache_locking.py, crds/tests/test_list.py, crds/tests/test_locking.py, setup.py
Revisions to cache locking to add support for filelock and multiprocessing locks,  as well as unit tests to demonstrate locks synchronizing or not synchronizing 5 processes depending on the CRDS configuration.  multiprocessing locks are now the default because they require no third party dependencies.  The lockfile module is still supported in CRDS should it prove workable in some context and be needed, however,  multiprocessing unit tests demonstrated that it doesn't work for that use case.  Both filelock (preferred) and lockfile (deprecated) are CRDS dependencies in setup.py and supported by conda as verified by Travis.  CRDS_LOCKING_MODE=filelock is necessary for multiple terminal windows / process trees.   The pipeline is still configured without locking,  running the cache readonly …
=> Cache locking

crds/sync.py
Simplified --clear-pickles in the crds.sync command line tool to wipe out all context pickles instead of only those implied by the contexts specified.   This is better for server mirroring and/or debugging with end users.
=> Simplify clear pickles

crds/sync.py
This is to prevent updating the default content in the pipeline when files are not available for download (yet) in the archive.  And also more generally for other errors.  It prevents switching to a default the cache doesn't have.
=> Added code to crds.sync to inhibit context updates following errors

crds/jwst/tpns/nirspec_all.tpn, crds/jwst/tpns/nirspec_all_ld.tpn
To support old test data as directed in Jira-CRDS-154.
=> Added STRIPE and S1600A1 back as NIRSPEC SUBARRAY names 

crds/bestrefs/__main__.py, crds/bestrefs/bestrefs.py, crds/bestrefs/headers.py, crds/certify/certify.py, crds/jwst/gen_system_crdscfg.py, crds/list.py, crds/matches.py, crds/misc/check_archive.py, crds/misc/sql.py, crds/misc/uniqname.py, crds/refactoring/checksum.py, crds/refactoring/newcontext.py, crds/refactoring/refactor2.py, crds/rowdiff.py, crds/submit/monitor.py, crds/sync.py, crds/tests/test_bestrefs.py, crds/tests/test_diff.py, crds/tests/test_list.py, crds/uses.py
Changes docs like "python -m crds.list" to "crds list",  where the latter master script hides internal CRDS package structure.
=> Updated docstrings for CRDS master script

crds/certify/validators.py
Missing numerical values are defined as UNDEFINED leading to confusing failure modes when numerical expressions use them.   This update makes CRDS screen the header for UNDEFINED values contained in expressions and abort checks early with better diagnostics.
=> Modified certify's expression validator to handle missing keyword values

crds/jwst/tpns/all_photom.tpn, crds/list.py, crds/tests/test_certify.py
Made PIXAR_SR and PIXAR_A2 optional for all JWST PHOTOM references.
Also includes  code to prefix output of crds list --cat with filename of file being catted making more of the output suitable for grep'ing etc.
Updated unit test for JWST CAL  data models validation errors.
=> Certify2 constraint updates

crds/certify/certify.py, crds/refactoring/refactor2.py, crds/sync.py, crds/tests/test_certify.py
Simplified complex main() methods in certify and sync based on cyclomatic complexity reported by Radon tool.  Definitely removed some convoluted logic and corner case bugs.
=> Radon simplify

crds/core/rmap.py, crds/tests/test_refactor.py, crds/tests/test_rmap.py, crds/tests/test_uses.py
InstrumentContext.get_filekinds() was originally a test support method.  I later used it to implement "default type determination" for JWST needed by CRDS repro where CRDS is not being told directly by CAL what type is needed.   Because of a case mismatch with the values returned by crds.jwst.locate.header_to_reftypes(),  the default type determination for JWST getreferences() and getrecommendations() was basically "all types".   This case change makes the intersection between "types recommended by header_to_reftypes()" and "available types in this context" work correctly and request only the required subset of available types.    This prevents spurious bestrefs errors for unneeded types.
The original bug didn't affect JWST CAL or HST bestrefs.  It was limited to requesting too many types …
=> Switched rmap.InstrumentContext.get_filekinds() values to lower case 

crds/bestrefs/headers.py
The JWST archive parameter web service returns an odd abstract form of dataset ID to name reprocessing or debug parameters:
fileSetName.Detector
Unfortunately users gravitate to:
fileSetName_Detector
which is both a very subtle difference and normal everywhere else.
Hence CRDS attempts to support both forms of ID.
CRDS bestrefs issues a warning if it requests but does not receive parameters for some ID.  It is a direct check independent of parameter service error handling.
Because headers are returned in the canonical fileSetName.Detector form,  but the command line value used fileSetName_Detector,  the warning check failed and was issued spuriously when parameter data was returned normally.
This tweak fixes that.
=> Added code to normalize JWST dataset ID format to fileSetName.Detector

crds/certify/certify.py, crds/io/abstract.py, crds/tests/test_certify.py
Issues warning only for ASDF extensions.
Restored categorization of JWST data models "is not one of" ValidationWarning
to CRDS ERROR, a CAL relocation of ValidationWarning from
jwst.datamodels.properties to jwst.datamodels.util broke it this time.
=> certify fitsverify output processing, ValidationWarning ERROR

crds/certify/validators.py, crds/tests/test_certify.py
Used to prevent evaluation of expressions with "UNDEFINED" values which cause confusing exceptions when used in concert with numerical values since one parameter is a string and the other a number.   This improves over the previous implementation by scanning the expression for identifiers directly instead of checking for known keywords that are UNDEFINED.   The previous technique would miss identifiers appearing only in the expression.
=> Revised the way CRDS certify scans expressions for identifiers

crds/jwst/tpns/nirspec_all.tpn, crds/jwst/tpns/nirspec_all_ld.tpn, crds/jwst/tpns/nirspec_dark.tpn, crds/jwst/tpns/nirspec_gain.tpn, crds/jwst/tpns/nirspec_linearity.tpn, crds/jwst/tpns/nirspec_readnoise.tpn, crds/jwst/tpns/nirspec_saturation.tpn, crds/jwst/tpns/nirspec_superbias.tpn
Modified the NIRSPEC constraints for GAINFACT so that:
1. GAINFACT is required for the GAIN reftype
2. GAINFACT is recommended for documentation, with a warning when absent, for several other types
3. GAINFACT is a R (real)
4. The model path is META.EXPOSURE.GAIN_FACTOR
=> Jira CRDS-175 nirspec gainfact

crds/io/tables.py
Since HST uses predominantly BIN tables (maybe only!),  ASCII tables are now supported but generate a warning.
=> Modified generalized table I/O to work with ASCII FITS tables

crds/certify/certify.py, crds/core/log.py, crds/tests/test_certify.py
fitsverify reports JWST CAL data models ASDF extensions as errors.  Since these were expected,  CRDS originally demoted these to WARNING messages.   Later it became apparent that they should instead be demoted all the way to CRDS INFO messages to avoid forcing tedious reviews of expected warnings.   
In the process,  I also generalized and streamlined the CRDS code which recategorizes fitsverify output.  In the case of checksum warnings,  the warning messages are recategorized as CRDS ERROR messages instead using the same mechanism.
Although these ASDF extension errors are new, they're resulting due to increased use of the data models when creating references,  so they are an expected feature of future files.
=> Modified certify --run-fitsverify to demote ASDF extension errors

crds/client/api.py, crds/core/rmap.py
Simplifies/removes logging for CRDS for DMS CAL runs for:
1. Message for reference type defined as N/A at instrument level
2. Message for skipping NOT FOUND reference file downloads
=> Increased verbosity level of two debug messages

crds/list.py
Trivial error handling and output formatting changes to make crds list work better for files not yet in CRDS.
=> Modified crds.list --cat handling of unavailable file catalog info

TESTING, crds/jwst/gen_system_crdscfg.py, crds/jwst/jwst_system_crdscfg_b7.1.1.yaml, crds/jwst/jwst_system_crdscfg_b7.1.3.yaml, crds/jwst/pipeline.py
This pull applies to CCD-39 and CCD-40,  tickets associated with updating CRDS repro required types handling for JWST B7.1.3.    Updates included consideration of the TSO pipeline and handling for NIS_WFSS,  as well as changes in CAL Step reference file usage in a few places.
This scheme remains a placeholder preceding the "better world" in which rmaps are smart enough that it is no longer needed.   For now,  it is feasible to update rapidly without CRDS deliveries,  but has the significant flaw that CAL and CRDS repro handle required REFTYPEs differently.
This pull also includes some unrelated docs on TEST cache maintenance.
The commit trail reflects some badly done git rebasing,  but manual review of the diffs looks good and unit tests pass.
=> Updates for system crdscfg references, CRDS repro required types

crds/client/api.py, crds/client/proxy.py, crds/core/config.py
Extended CRDS cache syncing download configuration options so they show up under "crds list --config" and also so it's possible to override sha1sum and file length failures which force immediate deletion of bad downloaded files.  These were needed to help troubleshoot bad files which were somehow delivered into the B-string archive while being correctly represented on the B-string CRDS server;  the discrepancy made them impossible to download normally,  env vars can now be set to keep bad files for debug purposes.
=> Sync retries and config options

crds/core/rmap.py, crds/diff.py
Fixes the ability of the crds diff command line tool to compare two different caches instead of the more normal case of diffing files within a single cache.
=> Ccd 116 cache to cache differences

crds/core/selectors.py
Rmap code doing updates replacing degenerate syntax 'N/A' with a nested UseAfter selector containing a real file was using add_item instead of replace_item.
=> Fixed bug for rare rmap update case

crds/core/selectors.py
Addresses a problem for rmap updates for e.g. COS DEADTAB.
=> Bugfix for CCD-114 Selection comparison of e.g. 'FUV' and ('NUV',)

crds/core/git_version.py
=> Updated git hash for end-of-July version of CRDS as 7.2.5

setup.py
Eliminates warnings about install_requires, extras_require, tests_require.
=> Added "import setuptools" to setup.py

crds/core/cmdline.py
Modified handling of mapping resolution for instrument "all" for cases where a type is N/A for an instrument.   These N/A instruments are just dropped from processing.   The all wildcard makes it possible to work on all instruments without spelling them all out.
=> Fixed handling of abstract contexts like jwst-all-specwcs-edit

crds/core/utils.py, setup.py
Adding import setuptools caused problems with installing the crds.server sub-package.  Consequently,  the sub-package was moved to a standalone crds_server package.  The utils.get_object() function was modified to permit crds_server as a leading path.   These changes are required in lock step to support the renamed server package.
=> Restore import setuptools,  Enable get_object() crds_server

crds/certify/certify.py, crds/core/cmdline.py, crds/diff.py, crds/refactoring/checksum.py, crds/refactoring/refactor.py, crds/rowdiff.py, crds/tests/test_certify.py, crds/tests/test_cmdline.py, crds/tests/test_diff.py, crds/tests/test_uniqname.py
Previously CRDS command line tools typically interpreted file names with no path to mean "the path is in the CRDS cache".   This reverts CRDS to normal UNIX semantics where a pathless file is intepreted to be in the current working directory.
=> Updated path handling for command line tools

crds/misc/get_synphot.py
clarify meaning of --keep-crds and --keep-synphot
=> Improved get_synphot help text,  switch names

setup.py
since CRDS refers to many resources relative to __file__.
=> Added zip_safe=False to setup.py 

crds/client/api.py
Use the default context associated with the current server if the user doesn't specify pipeline_context.   
This facilitates simple downloads of specific files which don't care much about context.
=> Enhance client.api.dump_files() 

crds/core/config.py
This should re-enable password prompts if you don't put authentication info in $HOME/.crds.ini
=> Fixed bugs in get_username() and get_password() 

crds/core/utils.py, crds/submit/submit.py
Assumes the CRDS server ingest directory is directly visible to end users
on a local file system mount,  e.g. /grp/crds/ingest/jwst/ops/homer;  this
eliminates the need for using pldmsins1.stsci.edu as a gateway system, ssh setup, etc.
Added explicit chmod to crds.core.utils.create_path().
=> Simplified file submission copying and ingest directory setup

crds/core/utils.py, crds/submit/submit.py
Removed (hopefully) last vestiges of crds submit "ssh dependency" from the --wipe switch which removes existing files from the ingest directory.   Run on a non-gateway it would ssh to the gateway before trying to remove files.
Added an exception trap around new os.chmod function call added to force ingest directory permissions on the server while disregarding umask.
=> Simplify ingest copy,  drop ssh dependency

crds/submit/rc_submit.py
async cannot be used as a function keyword parameter in Python-3.7.   Was blocking installs for other work on extend-batch-submit.
=> Renamed "async" parameter in the rc_concept submit() function 

crds/certify/certify.py
more warning when fitsverify isn't running right.
=> Mapped "dyld: Library not loaded:" to a warning so certify users get

crds/certify/certify.py, crds/certify/check_sha1sum.py, crds/core/exceptions.py
This changes the behavior of the website to report sha1sum issues as "bad files" rather than as submission failures which technically should be limited to server malfunctions.
=> Refactored duplicate file / certify sha1sum checking

crds/core/git_version.py, crds/submit/submit.py
due to issues with availability of unreleased or unsynced rmaps.
=> Turned off API certify check for rmap updates 

crds/core/log.py
Found second location where .propagate=False was needed.
=> Fixes logging double vision 

crds/core/config.py, crds/sync.py
Modified "crds sync --files ... --output-dir ..." to eliminate junk files and unwanted instrument directory structure.
=> Simplify crds sync --files

documentation/crds_users_guide/source/programmatic_interface.rst
Renamed DARKFILE to DARK for JWST conventions.
Dropped section on password and  consolidated with auth.mast intro.
=> Programmatic API tweaks

documentation/crds_users_guide/source/programmatic_interface.rst
Added additional information and links to programmatic API section on authentication,  restoring the cautionary note not to enter AD passwords directly into CRDS.
=> Update programmatic api authentication

crds/hst/specs/combined_specs.json, crds/hst/specs/synphot_thermal.rmap, crds/hst/specs/synphot_thruput.rmap, crds/hst/specs/wfc3_bpixtab.spec
HST synphot type specs corrected from CREATED to DATE.
WFC3 BPIXTAB type spec drops unique_rowkeys due to excessive change output.
New generated combined_specs.json
=> Update HST type specs

crds/client/api.py, crds/submit/submit.py
https://jira.stsci.edu/browse/CCD-388
Per Todd, all we need to do here is remove the call to get_submission_info -- since files are being uploaded over HTTPS now, there's no reason why anyone would need a filesystem path.
=> Remove unnecessary call to get_submission_info

crds/hst/specs/combined_specs.json, crds/hst/specs/wfc3_bpixtab.spec
On review,  Matt M. thought our recent issues with BPIXTAB massive pixel changes may be a one-off and requested that I restore the BPIXTAB table check.
=> Restored the WFC3 BPIXTAB table check

crds/submit/web.py
https://jira.stsci.edu/browse/CCD-374
With this change, we'll be checking the HTTP status code of server responses and throwing an appropriate exception when it's >= 400.
@jaytmiller let me know if there's anything else to do here.  This at least will be more comprehensible than the JSON parsing errors we had before.
=> Handle HTTP error status codes from the server

crds/core/pysh.py
Enables trapping failed commands using pysh.set_debug(True) without extra output clutter.
=> Turned off trace_commands and capture_output by default for pysh

crds/core/exceptions.py, crds/core/utils.py
Added a CRDS exception which can be caught during file submissions at very early stages of processing which nevertheless need  to identify bad files.    This is handles failure to compute (instrument, reftype) due to malformed ASDF CCD-553 during instrument locking prior to running certify.
=> Added FilePropertiesError exception

crds/core/custom_dict.py
Fixes the following DeprecationWarning under Python 3.7 (deprecated under 3.8):
```
../crds/core/custom_dict.py:10: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
from collections import MutableMapping
```
=> Fix collections.abc deprecation

crds/core/cmdline.py, crds/sync.py
modified crds sync to avoid downloading bad files when --purge-rejected or --purge-blacklisted are set.   This prevents a download-purge loop.   Fixed some log message typos,  docstring.
=> For CCD-560 improve sync purging

crds/core/config.py
Fixed bug in crds.core.config regex which parses CRDS-style filenames and underpins the config.is_mapping() utility function.  The bug results in an incorrect response for name fields containing digits,  such as HST instruments wfc3 and wfpc2,  potentially causing valid mapping names to be rejected or mischaracterized.
=> Fix bug in filename parsing regex

crds/client/api.py, runtests
This is an interesting story!  It turns out that `os.system` doesn't just return the exit status of the executing command:
```
exit status indication: a 16-bit number, whose low byte is the signal number that killed the process, and whose high byte is the exit status (if the signal number is zero); the high bit of the low byte is set if a core file was produced.
```
Since nosetests exited with status 1, and the process wasn't killed, we had high byte 0x01 and low byte 0x00, which is the integer 256.  It turns out that exit status is only allowed in the range 0-255, so when you call sys.exit(status), it performs mod 256 on the input before passing it along.  256 mod 256 = 0 so in the end we were reporting success.
I checked both the server and client code for cases where we're using the …
=> Fix for runtests return value

crds/client/api.py, crds/core/heavy_client.py
Moved decoding of download_metadata from get_server_info() into its own cached dedicated function based on server info.  Removed direct references to download_metadata from heavy_client.   This should both simplify and optimize by avoiding decoding of download_metadata when not being used.
=> Improve download_metadata

crds/jwst/tpns/miri_reset.tpn
This is part of completing the type setup last worked on in 2014.
=> Corrected MIRI RESET array shape constraints

crds/certify/certify.py
For ccd-583.  HEASARC convention Astropy doesn't support and after consideration closed without implementing since FITS standards now permit CONTINUE cards.
=> Downgraded fitsverify warning about LONGSTRNG to info

crds/sync.py
Added args.purge_blacklisted and args.purge_rejected (bad mappings or references respectively) as driver for sync.verify_files since verification is required for purging.   This is related to removing bad files from /grp/crds/cache so they don't get used accidentally.
=> Simplified use of sync --purge-rejected and --purge-blacklisted

README.rst, crds_setup_all, crds_setup_crds, crds_setup_env, setup.py
Refactored crds_setup_env into 3 pieces:
crds_setup_all  -- installs both base conda and CRDS s/w + dependencies
crds_setup_env  -- installs base conda and creates crds-env
crds_setup_crds -- installs CRDS + dependencies into current env
The new setup scripts normally require no parameters.
The new env setup enables selection of OS shell (bash,csh,zsh) and
install location.
The new env setup enables selection of the install directory.
Pip installs now also --upgrade.
Refectored dependency groups some to streamline submission+test install.
Added bandit and jupyterlab as test + dev dependencies.
Updated README.rst
=> Improved environment setup scripts

setup.py
Added pip dependencies only needed for file submissions to install_requires so that everything needed to run CRDS (except C-based fitsverify) for file submissions will install automatically when CAL s/w is installed.
=> Add file submission dependencies to base install

setup.py
Added awscli and helm (not really required) as CRDS aws and dev group dependencies respectively.  awscli is required by sync plugin scripts.
=> Add additional dependencies

crds/core/mapping_verifier.py
Needed for Python-3.8 support,  adds new whitelisted AST node.
=> Added visit_Constant to mapping_verifier

.travis.yml
Introduced to correct the following errors in the Travis build logs:
OS-X:
CRDS - INFO -  >> dyld: Library not loaded: @rpath/libcfitsio.6.dylib
Linux:
CRDS - INFO -  >> fitsverify: error while loading shared libraries: libcfitsio.so.6: cannot open shared object file: No such file or directory
Edit: The problem here seems to stem from the fact that last month conda also started publishing cfitsio on their own via a conda-feedstock recipe. This package provides `cfitsio 3.470` whereas Astroconda is currently only providing `3.440`. A rebuild of `fitsverify` should correct this and will be provided soon.
=> Add missing dependency to Travis environment

crds/misc/query_affected.py
Changed query_affected.py to handle backward context transitions better and produce no output.
=> Improve handling of backward context transitions (repro)

crds/core/heavy_client.py, crds/tests/test_bestrefs.py, crds/tests/test_cmdline.py, setup.py
Modified the server config fetch in heavy_client.py to operate directly from S3
instead of via download plugin whenever CRDS_CONFIG_URI is set.  Strictly
speaking URI can be a URL or a file, but generally we only use s3://.
Optimized unit tests for time from 880 seconds to 280 seconds on mac laptop.
Added nose-cprof and coverage to the dev dependency group of setup.py.
=> Change to S3 server config load + unit test optimization + setup dependencies.

crds/tests/test_locking.py
Elided doctest output check for unlocked locking doctests which only passed coincidentally since locking was disabled.   Revised tests still smoke test CRDS with locking disabled.
=> CCD-645 Fix bad locking doctests

crds/hst/tpns/synphot_syn.tpn, crds/hst/tpns/synphot_syn_ld.tpn
This PR adds an additional check that warns if the first and last THROUGHPUT values of a synphot component table are nonzero.  This is a check that ReDCaT currently performs manually as part of their delivery process.  Matt says it should be only a warning, since there are some special cases where nonzero values are permitted.
I tested this on a handful of existing files, and modified a file to have a nonzero value and witnessed the warning.
=> Additional certify check for synphot component tables

crds/tests/test_certify.py
This updates the doctest expected output to include the cal code's error.
=> Update ASDF 'opaque name' test to expect cal code error

crds/jwst/specs/combined_specs.json, crds/jwst/specs/nircam_apcorr.rmap
From further discussion of the NIRCam APCORR files, [JP-315](https://jira.stsci.edu/browse/CRDS-315), basing the reference files on DETECTOR was determined to be incorrect. Formally removing the selection criterion from the code spec.
=> Remove DETECTOR from nircam_apcorr spec definition

crds/hst/tpns/acs_ccd.tpn
Per Meaghan/Tyler, the column is required and should contain positive integers between 60,000 and 70,000.  I tested the certifier on their new files and saw only warnings about the new row format.
=> Add new ATODSAT column to ACS CCDTAB .tpn

crds/certify/reftypes.py, crds/list.py
Dumps out the TpnInfo lines associated with the specified files for use during type development.  See CCD-667.   This is for use during type development.  Basically:
crds list --tpns candidate-reference-file
=> Added --tpns switch to 'crds list'

setup.py
To support testing automation efforts it's helpful to have the URL of the source repository in the package metadata.
Adding `project_urls` dictionary to `setup.py` similar to other `spacetelescope` projects.
=> Add package metadata with source repo URL and others.

crds/submit/rc_submit.py, crds/submit/submit.py, crds/tests/test_submit.py
This adds a `context` parameter to `Submission.__init__`, and fixes a wee bug in `crds.submit.submit`, which was not posting `pmap_text` to the server.
=> Allow derived-from context to be specified when making a programmatic submission

crds/hst/specs/combined_specs.json, crds/hst/specs/wfc3_imphttab.spec, crds/hst/tpns/wfc3_imp.tpn
Four new columns were added to each binary table in the UVIS reference file (one of the column names varies by table).
=> Support new WFC3 IMPHTTAB columns

crds/hst/tpns/wfc3_imp.tpn
See note in the .tpn, but we're not going to be able to validate the type of the columns containing nested arrays, because `FITS_rec` is not reporting the correct type for those columns.
=> Adjust WFC3 IMPHTTAB .tpn

crds/core/selectors.py, crds/tests/test_reftypes.py, documentation/crds_users_guide/source/file_submissions.rst
Our users prefer that merge_overlaps defaults to true for JWST as well.  I'll be running the JWST regression tests with this branch to confirm that nothing goes haywire with this change and will comment here with the results.
EDIT: Regression tests passed no problem.  This seems ready to go.
=> Change merge_overlaps default to true for all observatories

crds/roman/locate.py
Forgot a character, discovered this when attempting to initial .pmap and .imap for Roman WFI.
=> Fix typo in name of stdatamodels package

.travis.yml, crds/tests/test_certify.py, crds/tests/test_locking.py, crds/tests/test_reftypes.py, crds/tests/test_substitutions.py, setup.py
We added some initial Roman rules files in https://github.com/spacetelescope/crds-cache-test/pull/5, so we should now be able to run some basic tests.  I looked through the existing JWST and HST-specific tests and added Roman versions where appropriate (except for the "certify a mapping" and "certify a reference" test cases that @PaulHuwe is working on).
=> Add some basic tests of Roman support

crds/jwst/specs/combined_specs.json, crds/jwst/specs/miri_apcorr.rmap
MIRI is changing the format of the APCORR reference files that will no longer be using FITS tables. Remove the column verification.
=> Remove row checking requirement for miri apcorr

crds/jwst/tpns/fgs_all.tpn
As per [JP-1807](https://jira.stsci.edu/browse/JP-1807), new FGS subarrays are being created which will need reference files. Add the subarrays to the valid list.
=> Add new FGS subarrays for ASIC tuning

crds/jwst/tpns/fgs_all.tpn
GitHub doesn't show it well on the diff, but there is a trailing zero-width space on the end of `SUBIDSTRIPLL​`.
=> Remove rogue whitespace from FGS subarray name

crds/roman/__init__.py
Roman reference files don't currently include a META.MODEL_TYPE so this results in a warning in the certifier output when --dump-provenance is enabled.
=> Remove META.MODEL_TYPE from Roman 'provenance' keywords

crds/jwst/gen_system_crdscfg.py, crds/jwst/locate.py, crds/roman/locate.py
`DataModel.to_flat_dict` returns NDArrayType instances even when include_arrays=False.  We'll need to fix that in stdatamodels, but this will stabilize our tests in the meantime.
=> Cover for bug in DataModel.to_flat_dict

crds/hst/locate.py, crds/io/abstract.py, crds/jwst/locate.py, crds/roman/locate.py
In crds 10.2.0 we changed the`@hijack_warnings` decorator to call an observatory-specific plugin so that we could support both Roman and JWST.  Unfortunately the `utils.file_to_observatory` method (indirectly) calls a method wrapped with that decorator, which means you need the observatory to determine the observatory, which results in the software defaulting to "jwst", which breaks `crds bestrefs` calls on HST data in certain environment variable configurations.
This PR changes `@hijack_warnings` back to its original form.  This is possible because Roman and JWST now share code in stdatamodels so there is no longer a need to catch different warnings depending on the observatory.
The two failing tests are due to an unrelated change in a Roman schema.
=> Remove observatory-specific plugin for hijack_warnings

crds/hst/specs/acs_satufile.rmap, crds/hst/tpns/acs_sat.tpn
It has come to light that the ACS SATUFILE will need to match on CCDAMP for one of the detectors.  We're allowing N/A because the file for the WFC detector will not.
=> Add CCDAMP to ACS SATUFILE parkey

setup.py
At least some basic crds functions fail without asdf (`crds list --resolve-contexts --contexts` on a JWST cache, for example), so it seems that we should list it as a requirement instead of relying on the jwst or romancal packages to bring it in.
=> Add asdf to install_requires

crds/jwst/specs/combined_specs.json, crds/jwst/specs/nircam_extract1d.rmap
Errors in the tests clued us into the fact that this rmap was delivered before the spec existed.  I filed a separate issue to investigate how that's possible.
=> Add support for nircam extract1d

crds/hst/tpns/cos_1dx.tpn, crds/hst/tpns/cos_1dx_ld.tpn, crds/hst/tpns/cos_2zx.tpn, crds/hst/tpns/cos_2zx_ld.tpn, crds/hst/tpns/cos_disp.tpn, crds/hst/tpns/cos_disp_ld.tpn, crds/hst/tpns/cos_flat.tpn, crds/hst/tpns/cos_flat_ld.tpn, crds/hst/tpns/cos_lamp.tpn, crds/hst/tpns/cos_lamp_ld.tpn, crds/hst/tpns/cos_phot.tpn, crds/hst/tpns/cos_phot_ld.tpn, crds/hst/tpns/cos_profile.tpn, crds/hst/tpns/cos_profile_ld.tpn, crds/hst/tpns/cos_trace.tpn, crds/hst/tpns/cos_trace_ld.tpn, crds/hst/tpns/cos_wcp.tpn, crds/hst/tpns/cos_wcp_ld.tpn
COS will be delivering reference files with LIFE_ADJ=5 this year, and LIFE_ADJ=6 in 2022.  I don't see the harm in accepting both early.
=> Add 5 and 6 to the permissible COS LIFE_ADJ values

crds/core/utils.py, documentation/crds_users_guide/source/environment.rst, envs/s3.sh, scripts/crds_s3_get
Some useful updates to the crds_s3_get script:
- Add retries.  We've been seeing some transient errors from S3 and this will save pipeline operators from having to investigate and rescue jobs.
- Add optional checksum and file size verification
=> Add retries and optional checksum and file size verification to crds_s3_get

crds/jwst/gen_system_crdscfg.py, crds/jwst/jwst_system_crdscfg_b7.8.yaml, crds/jwst/pipeline.py
Resolves [CCD-1011](https://jira.stsci.edu/browse/CCD-1011)
The CRDSCFG file has been updated to include a number of special exposure types and consider them "normal" processing.
The file itself is part of a hard-to-maintain system and should be deprecated in the very near future. This PR is considered a temporary fix for current users to keep a base level of operation.
=> CCD-1011 Update CRDSCFG for NRS_LAMP handling

crds/jwst/tpns/miri_dark.tpn, crds/jwst/tpns/nirspec_area.tpn
This PR fixes two mistakes in the new META.MODEL_TYPE validations that became evident as we started validating existing files.
=> Fix model type validations in nirspec_area.tpn and miri_dark.tpn

CHANGES.rst, crds/hst/tpns/acs_imp.tpn, crds/hst/tpns/stis_imp.tpn
The .tpn for STIS did not include all the permitted values, and ACS was missing them entirely.
=> Update STIS and ACS IMPHTTAB DATACOL validations

CHANGES.rst, crds/hst/tpns/synphot_syn.tpn, crds/hst/tpns/synphot_syn_ld.tpn, crds/hst/tpns/synphot_th.tpn, crds/hst/tpns/synphot_th_ld.tpn, crds/tests/test_bestrefs.py, crds/tests/test_synphot_hst.py
LITREF should be an optional string-type keyword but we'll display a warning when it is missing.
=> Add LITREF to synphot component tpns

CHANGES.rst, crds/client/api.py, crds/client/proxy.py, crds/core/config.py, documentation/crds_users_guide/source/environment.rst
For JSON RPC calls to the server, the default timeout for network operations is None, which means never time out. Though this has not been an issue before, recent events, as documented in CCD-1161, have shown otherwise.
A new environment, CRDS_CLIENT_TIMEOUT_SECONDS, is implemented, with a default value of 60.
=> CCD-1161 Implement timeout on CRDS Server network requests

CHANGES.rst, crds/core/utils.py
These simple changes allows the CRDS operations for **'crds.bestrefs.assign_bestrefs()'**, and any other CRDS function that uses these functions, to operate under Windows while keeping the exact same functionality under all other OS's.
The changes were tested under a version of CRDS which was installed simply using **'pip install -e .'** from a local clone of the CRDS code into an existing Python 3.8 conda environment under Windows 10.  In fact, the revised code was tested by updating a WFPC2 observation using the command: 
**crds.bestrefs.assign_bestrefs(['u5b8060pr_c0m.fits'], sync_references=True)**
The updated file was then able to be processed using STWCS later confirming that everything worked as expected for any CRDS installation.
=> Enable bestrefs I/O under Windows

CHANGES.rst, crds/core/selectors.py, crds/tests/data/roman_wfi_flat_ewsc.rmap, crds/tests/test_certify.py, crds/tests/test_rmap.py
- Include reference filenames and useafter data in log messages for equal weight special case errors and warnings (resolves CCD-1213)
- Add non-HST test cases (Roman/JWST useafter date-time format)
- Update expected error and warning log message data/formatting for Ambiguous Match cases
=> CCD-1213/ewsc-detailed-logging

CHANGES.rst, crds/submit/rc_submit.py, crds/submit/submit.py, crds/submit/web.py
Roman pipeline authorized user can pass the --autoconfirm argument to automatically confirm reference file submissions as long as there are no errors. If there are errors, the submission is automatically canceled.
Minor updates to the file_map attribute for submission api script (no longer need to run "update_file_map()" - the script will try to get the renamed mappings and references even if the submission has not yet been confirmed (i.e. pmaps and imaps not actually generated yet).
=> CCD-1214 roman-pipeline-autoconfirmation

CHANGES.rst, crds/jwst/specs/combined_specs.json, crds/jwst/specs/miri_apcorr.rmap, crds/jwst/specs/miri_ipc.rmap, crds/jwst/specs/niriss_pars-chargemigrationstep.rmap, crds/tests/test_reftypes.py
This PR contains changes for CCD-1360, 1361 and 1362.
=> Rmap tickets for JWST build 10.0

pyproject.toml, test/refactoring/test_checksum.py
Resolves [CCD-1333](https://jira.stsci.edu/browse/CCD-1333)
WIP [CCD-1264](https://jira.stsci.edu/browse/CCD-1264)
This issue converts the checksum unit tests from nose/doctest to more pytest friendly.
=> CCD-1333 convert checksums tests from nose/doctest to pytest

CHANGES.rst, setup_test_cache
The script `setup_test_cache` always clears out the local cache completely. The command line argument is added to the script to allow only updating the local cache. The usage now is as follows:
```
./setup_test_cache CRDS_TEST_ROOT <c/u>
```
where `<c/u>` is an optional argument. If `c`, the default behavior of completely clearing and rebuilding the local cache is done. This is also the default behavior if no argument is given. If anything other that `c` is given, such as `u`, the cache will only be updated with the current state of the HST/JWST operational servers.
When run without any arguments, a help text is given.
=> Refactor setup_test_cache to allow for simply updating local cache

.github/workflows/ci.yml
It appears the that Pytest CI downloads the same test cache every time; perhaps this can be sped up by caching it per-context
=> use GitHub Actions cache to cache test cache

test/certify/test_certify.py, test/refactoring/test_newcontext.py, test/test_bad_files.py
Since the crds client code is meant to run locally, test should run locally with as little configuration as possible. There are still issues rooted in mission dependencies, but those should be handled in ensuring those are installed if the optional "test"] installation is chosen (not handled in this PR).
=> make tests more resilient to different environments

.github/workflows/cache.yml, .github/workflows/ci.yml, .github/workflows/contexts.yml, setup_test_cache
added a workflow specifically to cache CRDS reference files for subsequent testing, and have it run on a schedule every week so that the cache is ready upon a context change. This should force the cache to complete without having to run the tests first. Also, the caches are separated by observatory, so a change in one context should not necessitate redownloading the entire cache.
Additionally, set up a reusable workflow to retrieve the latest contexts of each server, that can potentially be used by other repositories.
=> add separate workflow to download CRDS test cache

.github/workflows/ci.yml
the Conda environment was hardcoded to `python=3.11` instead of `python=${{ matrix.python-version }}`
=> fix issue where environment was not using requested python version

CHANGES.rst, crds/jwst/specs/combined_specs.json, crds/jwst/tpns/miri_photom.tpn
Missing keywords in delivered miri photom reference files did not trigger an error with crds certify. This change should fix that.
=> (CCD 1385) Added PIXAR headers to MIRI PHOTOM

CHANGES.rst, crds/submit/rc_submit.py
Related to [CCD-1387](https://jira.stsci.edu/browse/CCD-1387)
The submission activity requires knowledge of the servers that are acceptable for submission. This PR replace JWST PUB with ROMAN TVAC.
=> remove jwst pub and add roman tvac to submission list

CHANGES.rst, crds/hst/tpns/cos_badt.tpn
Resolves CCD-1397
Allows specification of "N/A" for COS BADTTAB reftype references and rmaps.
=> CCD-1397: Add n/a to components of the cos badttab reftype

.github/workflows/cache.yml, CHANGES.rst
If other repositories (such as `stenv`) wish to run CRDS tests, and want to cache this testing data, then they can reuse the `cache.yml` workflow by calling
```yaml
jobs:
crds_test_cache:
uses: spacetelescope/crds/.github/workflows/cache.yml@master
```
However, currently the `actions/checkout` action does not specify which repo to checkout, meaning that when `cache.yml` is called in another repo, it will checkout THAT repo instead of `spacetelescope/crds`. This can be fixed by adding
```yaml
jobs:
- uses: actions/checkout@v3
with:
repository: spacetelescope/crds
```
=> explicitly specify CRDS in `actions/checkout` to enable reuse of caching workflow in other repos

.github/workflows/contexts.yml
there is the possibility that, when `contexts.yml` requests a context, the CRDS server returns an incorrect response. 
For instance, this happened yesterday:
https://github.com/spacetelescope/crds/actions/runs/7643167120/job/20824529761#step:2:8
```shell
echo "pmap=$( curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["hst"], "id": 1}' https://hst-crds.stsci.edu/json/ | python -c "import sys, json; print(json.load(sys.stdin)['result'])" )" >> $GITHUB_OUTPUT
```
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/usr/lib/python3.10/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File …
```
=> raise error if context is empty

CHANGES.rst, crds/jwst/specs/combined_specs.json, crds/jwst/specs/miri_pars-pixelreplacestep.rmap, crds/jwst/tpns/miri_pixelreplacestep.tpn
Deliveries have been made for pixel replace step yet we do not have existing specs or base rmaps for that reference type. This merge attempts to solve that.
=> Added rmap and tpn for pixel replace step.

CHANGES.rst, crds/certify/validators/core.py
An rmap for NIRISS NRM needs to have MODEL available for META.PEDIGREE. This change should ideally allow that.
=> MODEL was added to PEDIGREE verification for JWST.

.github/dependabot.yml
After this is merged, we should expect a PR from dependabot requesting to update at least the `actions/checkout` usage:
https://github.com/spacetelescope/crds/blob/d5d92a1c937d13f4a80360b9de71935e835e0d40/.github/workflows/ci.yml#L48
to version 4. Something like the following:
https://github.com/asdf-format/asdf/pull/1639
=> add dependabot for tracking github actions workflow version

documentation/crds_users_guide/source/reference_conventions.rst
The link to the jwst datamodels schemas in the documentation is currently broken:
https://hst-crds.stsci.edu/static/users_guide/reference_conventions.html?highlight=jwst#keywords-for-new-file-formats
This PR updates it to the current location of the schemas:
https://github.com/spacetelescope/stdatamodels/tree/main/src/stdatamodels/jwst/datamodels/schemas
=> fix jwst schemas link in documentation

CHANGES.rst, crds/certify/certify.py
ACS imphttab ref file submission was failing with the error:
2024-04-24 13:46:38,326 - CRDS - ERROR - In '20240423_acs_sbc_imp.fits' : Checking tables modes in segment 0 of #file_location : operands could not be broadcast together with shapes (52,) (54,)  
Error arises in the crds certify code when trying to compare table elements against the current reference file: the omparison errors when the array sizes are different, which can happen for these reference file types where the table cells contain variable length arrays
=> CCD-1464: Fix error when submitting acs imphttab ref files

CHANGES.rst, crds/jwst/specs/combined_specs.json, crds/jwst/specs/nircam_pars-darkcurrentstep.rmap, crds/jwst/specs/niriss_pars-darkcurrentstep.rmap, crds/jwst/specs/nirspec_pars-darkcurrentstep.rmap, test/core/test_reftypes.py
This PR handles CCD-1467 which added 3 rmaps for the pars-darkcurrentstep reference type.
=> Added pars-darkcurrentstep rmaps for NIRISS, NIRCAM and NIRSPEC.

crds/jwst/specs/combined_specs.json, crds/jwst/specs/nircam_pars-darkcurrentstep.rmap, crds/jwst/specs/niriss_pars-darkcurrentstep.rmap, crds/jwst/specs/nirspec_pars-darkcurrentstep.rmap
The original dark current step files I made had incorrect parkey selections. These new files should address that.
=> Adjusted parkeys for niriss, nircam and nirspec.

README.rst
This ticket is part of a slightly larger effort to remove mentions of astroconda from installation instructions.
=> CCD-1440 remove astroconda from installation instructions

test/certify/test_certify.py
@stscieisenhamer found a stray breakpoint in one of the certify test that triggers when the test fails. This PR removes the breakpoint.
=> remove breakpoint when test fails

changes/1089.general.rst, crds/client/api.py, pyproject.toml
Resolves [CCD-1521](https://jira.stsci.edu/browse/CCD-1521)
- Any 'dev' calibration software versions will now default to the Edit Context. 
- Added bs4 to submission dependency list
</details>
=> Drc dev versions

changes/1077.general.rst, crds/certify/certify.py, crds/certify/validators/synphot.py, crds/core/timestamp.py, crds/hst/siname.py, crds/submit/submit.py
* Replaces string literal with a raw string
* https://docs.python.org/3/library/re.html#module-re states: [..] any invalid escape sequences in Python’s usage of the backslash in string literals now generate a SyntaxWarning and in the future this will become a SyntaxError. The solution is to use Python's raw string notation for regular expression patterns.
This PR addresses ...
Under Python 3.10:
```
DeprecationWarning: invalid escape sequence '\.'
_VERSION_RE = re.compile(f"^[0-9]+\.[0-9]+\.[0-9]+$")
```
Under 3.11:
```
_VERSION_RE = re.compile(f"^[0-9]+\.[0-9]+\.[0-9]+$")
^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid escape sequence '\.'
```
Under 3.12:
```
SyntaxWarning: invalid escape sequence '\.'
_VERSION_RE = re.compile(f"^[0-9]+\.[0-9]+\.[0-9]+$")
```
<details><summary>news …
=> Fix re string type

CHANGES.rst, changes/1098.jwst.rst, crds/jwst/tpns/nircam_all.tpn
Resolves [CCD-1527](https://jira.stsci.edu/browse/CCD-1527)
This PR addresses the lack of the new subarray SUB8FP6A added being delivered for NIRCAM.
=> Added SUB8FP6A to nircam_all.tpn

pyproject.toml
removes unnecessary test dependencies `lockfile`, `pylint`, `flake8`, `bandit`, and `metrics-logger`, and adds `stsynphot` and `stdatamodels` to the `test` dependencies
</details>
=> prune unecessary dependencies

changes/1105.hst.rst, crds/hst/specs/combined_specs.json, crds/hst/specs/stis_halotab.spec
Resolves [CRDS-781](https://jira.stsci.edu/browse/CRDS-781)
Closes #
This PR addresses a typo in the text description for the STIS HALOTAB reference file, where 'Detector' is mis-spelt as 'Detectore'
</details>
=> CRDS-781: Fix typo in STIS halotab text

changes/1110.testing.rst, pyproject.toml
CRDS nightly Regtests have been failing due to dependency resolution by uv
UV is a fast Python package manager. It has a cache of built dependencies the same as pip.
This PR will resolve nightly regression test failures 
https://github.com/spacetelescope/RegressionTests/actions/workflows/crds_client.yml
Successful Regression Test: https://github.com/spacetelescope/RegressionTests/actions/runs/13507059096
Resolves https://jira.stsci.edu/browse/SPB-2406
The problem is an incompatibility with awscli and sphinx.
uv attempts resolves the whole project in cache including optional dependencies.
awscli is the real culprit - requiring docutils>=0.10, <0.17. The previous successfully solved environments downgraded awscli to 0.7.0 (circa Feb 2013) making it almost unrecognizable.
Why now?
The …
=> Declare conflicting optional dependencies for uv builds

.github/workflows/release.yml
Using the new hash format for github actions changed the create-release-action to v2 which fails. Changing this back to v1 so that we can avoid failures when deploying the release action.
=> revert release action version to v1

CHANGES.rst, changes/1108.roman.rst, changes/1110.testing.rst
Adding news fragments back in so that release action for 12.1.0 doesn't throw an error
=> fix-changelog

CHANGES.rst, crds/jwst/specs/combined_specs.json, crds/jwst/specs/niriss_sirskernel.rmap, crds/jwst/specs/nirspec_pars-darkcurrentstep.rmap, crds/jwst/specs/nirspec_pictureframe.rmap, crds/jwst/specs/nirspec_sirskernel.rmap, crds/jwst/tpns/nirspec_pictureframe.tpn
Resolves [CCD-1561](https://jira.stsci.edu/browse/CCD-1561)
This PR addresses the addition of the SIRSKERNEL reftypes for both NIRISS and NIRSPEC
=> Add reftypes for SIRSKERNEL to NIRISS and NIRSPEC

changes/1114.jwst.1.rst, changes/1114.jwst.rst, crds/jwst/specs/combined_specs.json, crds/jwst/specs/niriss_bkg.rmap, crds/jwst/tpns/nircam_all.tpn
Resolves [CCD-1566](https://jira.stsci.edu/browse/CCD-1566)
Resolves [CCD-1564](https://jira.stsci.edu/browse/CCD-1566)
- ``changes/1114.jwst.rst``: Created new reftype for niriss_bkg based on niriss_wfssbkg
- ``changes/1114.jwst.1.rst``: Added DHS subarray values to nircam_all.tpn
</details>
=> Created new reftype for niriss_bkg based on niriss_wfssbkg.

changes/1122.jwst.rst, crds/jwst/specs/combined_specs.json, crds/jwst/tpns/niriss_bkg.tpn
This pr is to address the lack of a tpn file for the new niriss_bkg reftype.
=> Added tpn for niriss_bkg

changes/1121.hst.rst, crds/hst/acs_common.py
Resolves [CCD-1210](https://jira.stsci.edu/browse/CCD-1210)
Closes #
This PR pushes back the date for using subarray specific bias reference files for ACS
</details>
=> Update pre_sm4 subarray date to reflect July 2022 ref file delivery

changes/1132.jwst.rst, crds/jwst/specs/nircam_bkg.rmap, crds/jwst/tpns/nircam_bkg.tpn
Resolves [CCD-1600](https://jira.stsci.edu/browse/CCD-1600)
This PR addresses the addition of nircam_bkg.rmap
</details>
=> Added base rmap for nircam_bkg and tpn file.

changes/1146.hst.rst, crds/hst/tpns/cos_1dx.tpn, crds/hst/tpns/cos_1dx_ld.tpn, crds/hst/tpns/cos_2zx.tpn, crds/hst/tpns/cos_2zx_ld.tpn, crds/hst/tpns/cos_disp.tpn, crds/hst/tpns/cos_disp_ld.tpn, crds/hst/tpns/cos_flat.tpn, crds/hst/tpns/cos_flat_ld.tpn, crds/hst/tpns/cos_lamp.tpn, crds/hst/tpns/cos_lamp_ld.tpn, crds/hst/tpns/cos_phot.tpn, crds/hst/tpns/cos_phot_ld.tpn, crds/hst/tpns/cos_profile.tpn, crds/hst/tpns/cos_profile_ld.tpn, crds/hst/tpns/cos_trace.tpn, crds/hst/tpns/cos_trace_ld.tpn, crds/hst/tpns/cos_wcp.tpn, crds/hst/tpns/cos_wcp_ld.tpn
Resolves [CCD-1624](https://jira.stsci.edu/browse/CCD-1624)
Closes #
This PR updates the COS tpn files to remove the list of allowed values for the LIFE_ADJ keyword.  This means there is no need to update these files every time the COS team introduces a new lifetime position.
</details>
=> Remove list of allowed values for LIFE_ADJ in COS tpns (CCD-1624)

test/data/roman/mkdata.py
roman_datamodels is deprecating maker_utils: https://github.com/spacetelescope/roman_datamodels/issues/525
This PR updates the test file generation script `test/data/roman/mkdata.py` to use the new `create_fake_data` API (added in roman_datamodels [0.26.0](https://github.com/spacetelescope/roman_datamodels/releases/tag/0.26.0)).
I don't believe this script is run as part of any CI tests. I manually ran the updated script and it succeeded. Let me know if further testing is helpful.
Given the changes in this PR I'd like to add a "no-changelog" label but am unable to do so.
- …
=> remove maker_utils usage from mkdata test script

crds/io/abstract.py, crds/jwst/locate.py
Change `ValidationWarning` import from stdatamodels from `stdatamodels.validate` (which is undocumented) to the documented and public `stdatamodels.exceptions`.
Let me know if you think this needs a changelog entry.
FWIW stdatamodels is working on clarifying some API (making private modules `_` prefixed). See https://github.com/spacetelescope/stdatamodels/issues/535
While search CRDS I found some tests that check for exact strings like the following:
https://github.com/spacetelescope/crds/blob/79f90eb6d483d2c604cd6a8642e47429d381c467/test/certify/test_certify.py#L619
These will fail when `util` is renamed to `_util` (one of the planned changes). That isn't addressed in this PR and given the test specificity can't be addressed until it starts to fail.
<details><summary>news fragment change …
=> use public import location for ValidationWarning
